### ISSUE TITLE
Errors when compiling openmpi-v5.0.x

### ISSUE THREAD

**Issue by oleotiger** [open-mpi/ompi#8727]
## Background information
I wanna use `--cpu-set` options of mpirun and it only works in newer version such as v5.0.x and master. But I have got errors when compiling openmpi.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
openmpi-v5.0.x-202103240304-c445397

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
```
./configure --prefix=/home/software/libs/openmpi-5.0.x --enable-mpi1-compatibility --with-ucx=/home/software/libs/ucx-1.9.0/ --with-knem=/home/software/libs/knem/1.1.3/  --with-ofi=/home/software/libs/libfabric-1.12.0 
 make -j 48 
make install
```

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 7.6.1810 (Core)
* Computer hardware:  Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
* Network type:  mellonax CX-5

-----------------------------

## Details of the problem

```
Making all in mca/btl/sm
make[2]: Entering directory `/home/software/software/openmpi-v5.0.x-202103240304-c445397/opal/mca/btl/sm'
  CC       btl_sm_module.lo
  CC       btl_sm_component.lo
  CC       btl_sm_frag.lo
  CC       btl_sm_send.lo
  CC       btl_sm_sendi.lo
  CC       btl_sm_get.lo
make[2]: Warning: File `../../../../opal/libopen-pal.la' has modification time 7.6 s in the future
  CC       btl_sm_put.lo
  CC       btl_sm_xpmem.lo
  CC       btl_sm_knem.lo
btl_sm_get.c: In function ‘mca_btl_sm_get_knem’:
btl_sm_put.c: In function ‘mca_btl_sm_put_knem’:
btl_sm_put.c:115:33: error: storage size of ‘send_iovec’ isn’t known
  115 |     struct knem_cmd_param_iovec send_iovec;
      |                                 ^~~~~~~~~~
btl_sm_get.c:135:33: error: storage size of ‘recv_iovec’ isn’t known
  135 |     struct knem_cmd_param_iovec recv_iovec;
      |                                 ^~~~~~~~~~
btl_sm_put.c:116:33: error: storage size of ‘icopy’ isn’t known
  116 |     struct knem_cmd_inline_copy icopy;
      |                                 ^~~~~
btl_sm_get.c:136:33: error: storage size of ‘icopy’ isn’t known
  136 |     struct knem_cmd_inline_copy icopy;
      |                                 ^~~~~
btl_sm_get.c:154:23: error: ‘KNEM_FLAG_DMA’ undeclared (first use in this function)
  154 |         icopy.flags = KNEM_FLAG_DMA;
      |                       ^~~~~~~~~~~~~
btl_sm_get.c:154:23: note: each undeclared identifier is reported only once for each function it appears in
btl_sm_put.c:134:23: error: ‘KNEM_FLAG_DMA’ undeclared (first use in this function)
  134 |         icopy.flags = KNEM_FLAG_DMA;
      |                       ^~~~~~~~~~~~~
btl_sm_put.c:134:23: note: each undeclared identifier is reported only once for each function it appears in
In file included from ../../../../opal/mca/threads/thread_usage.h:33,
                 from ../../../../opal/class/opal_object.h:126,
                 from ../../../../opal/class/opal_list.h:73,
                 from ../../../../opal/mca/base/mca_base_framework.h:19,
                 from ../../../../opal/mca/shmem/base/base.h:26,
                 from ../../../../opal/mca/btl/sm/btl_sm.h:49,
                 from btl_sm_get.c:20:
btl_sm_get.c:160:28: warning: implicit declaration of function ‘ioctl’ [-Wimplicit-function-declaration]
  160 |     if (OPAL_UNLIKELY(0 != ioctl(mca_btl_sm.knem_fd, KNEM_CMD_INLINE_COPY, &icopy))) {
      |                            ^~~~~
../../../../opal/include/opal/prefetch.h:44:55: note: in definition of macro ‘OPAL_UNLIKELY’
   44 | #define OPAL_UNLIKELY(expression) __builtin_expect(!!(expression), 0)
      |                                                       ^~~~~~~~~~
In file included from ../../../../opal/mca/threads/thread_usage.h:33,
                 from ../../../../opal/class/opal_object.h:126,
                 from ../../../../opal/class/opal_list.h:73,
                 from ../../../../opal/mca/base/mca_base_framework.h:19,
                 from ../../../../opal/mca/shmem/base/base.h:26,
                 from ../../../../opal/mca/btl/sm/btl_sm.h:49,
                 from btl_sm_put.c:20:
btl_sm_put.c:140:28: warning: implicit declaration of function ‘ioctl’ [-Wimplicit-function-declaration]
  140 |     if (OPAL_UNLIKELY(0 != ioctl(mca_btl_sm.knem_fd, KNEM_CMD_INLINE_COPY, &icopy))) {
      |                            ^~~~~
../../../../opal/include/opal/prefetch.h:44:55: note: in definition of macro ‘OPAL_UNLIKELY’
   44 | #define OPAL_UNLIKELY(expression) __builtin_expect(!!(expression), 0)
      |                                                       ^~~~~~~~~~
btl_sm_get.c:160:54: error: ‘KNEM_CMD_INLINE_COPY’ undeclared (first use in this function)
  160 |     if (OPAL_UNLIKELY(0 != ioctl(mca_btl_sm.knem_fd, KNEM_CMD_INLINE_COPY, &icopy))) {
      |                                                      ^~~~~~~~~~~~~~~~~~~~
../../../../opal/include/opal/prefetch.h:44:55: note: in definition of macro ‘OPAL_UNLIKELY’
   44 | #define OPAL_UNLIKELY(expression) __builtin_expect(!!(expression), 0)
      |                                                       ^~~~~~~~~~
btl_sm_put.c:140:54: error: ‘KNEM_CMD_INLINE_COPY’ undeclared (first use in this function)
  140 |     if (OPAL_UNLIKELY(0 != ioctl(mca_btl_sm.knem_fd, KNEM_CMD_INLINE_COPY, &icopy))) {
      |                                                      ^~~~~~~~~~~~~~~~~~~~
../../../../opal/include/opal/prefetch.h:44:55: note: in definition of macro ‘OPAL_UNLIKELY’
   44 | #define OPAL_UNLIKELY(expression) __builtin_expect(!!(expression), 0)
      |                                                       ^~~~~~~~~~
btl_sm_get.c:164:9: error: ‘KNEM_STATUS_FAILED’ undeclared (first use in this function)
  164 |     if (KNEM_STATUS_FAILED == icopy.current_status) {
      |         ^~~~~~~~~~~~~~~~~~
btl_sm_put.c:144:9: error: ‘KNEM_STATUS_FAILED’ undeclared (first use in this function)
  144 |     if (KNEM_STATUS_FAILED == icopy.current_status) {
      |         ^~~~~~~~~~~~~~~~~~
make[2]: *** [btl_sm_get.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [btl_sm_put.lo] Error 1
make[2]: Leaving directory `/home/software/software/openmpi-v5.0.x-202103240304-c445397/opal/mca/btl/sm'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/software/software/openmpi-v5.0.x-202103240304-c445397/opal'
make: *** [all-recursive] Error 1
```

**Comment by awlauria** [comment]
@oleotiger what compiler are you using?

**Comment by oleotiger** [comment]
> @oleotiger what compiler are you using?

Both knew and openmpi are compiling with gcc9. 3.0

**Comment by awlauria** [comment]
@oleotiger can you try pulling in https://github.com/open-mpi/ompi/pull/8728/commits/a4c961859b7b10e571ba4fb39f05617d0c46ae53 and see if that works for you

**Comment by awlauria** [comment]
v5.0.x: https://github.com/open-mpi/ompi/pull/8729
