### ISSUE TITLE
MTT static builds broken on master

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1624]
[MTT is showing](https://mtt.open-mpi.org/index.php?do_redir=2312) that static builds are broken on master with the following kinds of errors:

```
/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/orte/.libs/libopen-rte.a(orted_submit.o):/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/orte/../opal/class/opal_object.h:458:
multiple definition of `MPIR_being_debugged'
../../../ompi/.libs/libmpi.a(libdebuggers_la-ompi_debuggers.o):/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/ompi/debuggers/ompi_debuggers.c:162:
first defined here
/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/orte/.libs/libopen-rte.a(orted_submit.o):/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/orte/../opal/class/opal_object.h:460:
multiple definition of `MPIR_debug_state'
../../../ompi/.libs/libmpi.a(libdebuggers_la-ompi_debuggers.o):/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/ompi/debuggers/ompi_debuggers.c:167:
first defined here
/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/orte/.libs/libopen-rte.a(orted_submit.o):
In function `MPIR_Breakpoint':
/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/orte/orted/orted_submit.c:171:
multiple definition of `MPIR_Breakpoint'
../../../ompi/.libs/libmpi.a(libdebuggers_la-ompi_debuggers.o):/home/mpiteam/scratches/community/2016-05-02cron/yaHD/mpi-install/TBN4/src/openmpi-dev-3979-gda695a6/ompi/debuggers/ompi_debuggers.c:221:
first defined here
```

**Comment by jsquyres** [comment]
Per discussion on the teleconf today, @rhc54 is aware of this already.  It's a duplication of symbols for the debugger stuff between ORTE and OMPI.

And just as an additional confirmation, I did a git bisect and it looks like 6ac7929bd070f72252ce8fc51c08ccbc7db0153d is the commit that caused the issue (which I think Ralph already knew).

**Comment by jsquyres** [comment]
Fixed via 83c2d04aa34605afa6ad105d2a54bb8933aede08.
