### ISSUE TITLE
Build failure for open-mpi 4.0.5 on macOS Big Sur (11.0.1)

### ISSUE THREAD

**Issue by fxcoudert** [open-mpi/ompi#8218]
### Background information

Trying to build open-mpi 4.0.5 from source on macOS Big Sur (11.0.1), with system compiler clang 12, for distribution in Homebrew. Build fails, in condition where it works with previous macOS version (10.13 to 10.15).

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Released 4.0.5

### Please describe the system on which you are running

-----------------------------

## Details of the problem

We are building with:

```
./configure --prefix=/usr/local/Cellar/open-mpi/4.0.5 --disable-dependency-tracking --disable-silent-rules --enable-ipv6 --with-libevent=/usr/local/opt/libevent --with-sge && make all
```

The build fails with:

```
   CCLD     libmca_common_sm.la
 Undefined symbols for architecture x86_64:
   "_mca_allocator_component_lookup", referenced from:
       _common_sm_mpool_create in common_sm_mpool.o
   "_opal_allocator_base_framework", referenced from:
       _common_sm_mpool_create in common_sm_mpool.o
   "_opal_class_init_epoch", referenced from:
       _attach_and_init in common_sm.o
   "_opal_class_initialize", referenced from:
       _attach_and_init in common_sm.o
   "_opal_compare_proc", referenced from:
       _mca_common_sm_local_proc_reorder in common_sm.o
   "_opal_hwloc_base_membind", referenced from:
       _mca_common_sm_mpool_alloc in common_sm_mpool.o
   "_opal_list_item_t_class", referenced from:
       _mca_common_sm_module_t_class in common_sm.o
   "_opal_output", referenced from:
       _attach_and_init in common_sm.o
       _common_sm_mpool_create in common_sm_mpool.o
   "_opal_proc_local_get", referenced from:
       _attach_and_init in common_sm.o
   "_opal_shmem_ds_copy", referenced from:
       _attach_and_init in common_sm.o
   "_opal_shmem_segment_attach", referenced from:
       _attach_and_init in common_sm.o
   "_opal_shmem_segment_create", referenced from:
       _mca_common_sm_module_create_and_attach in common_sm.o
   "_opal_shmem_segment_detach", referenced from:
       _attach_and_init in common_sm.o
       _mca_common_sm_fini in common_sm.o
   "_opal_shmem_unlink", referenced from:
       _mca_common_sm_module_unlink in common_sm.o
   "_opal_show_help", referenced from:
       _attach_and_init in common_sm.o
   "_opal_strerror", referenced from:
       _attach_and_init in common_sm.o
   "_opal_uses_threads", referenced from:
       _sm_module_finalize in common_sm_mpool.o
```

The full log (configure and make) is here: https://gist.github.com/fxcoudert/3c1b490d7f4c6fd0e11e394d992e5cbf

**Comment by ggouaillardet** [comment]
@fxcoudert thanks for the report!

@jsquyres do you have any recollection on why `libmca_common_sm.la` does **not** depend on `libopen-pal.la` ?
(other plugins such as `mca_btl_self.so` do depend on `libopen-pal.la`).

**Comment by fxcoudert** [comment]
What I am wondering is why this same issue is *not* triggered on macOS 10.15, with the same compiler. On macOS 10.15, the exact same build succeeds.

**Comment by ggouaillardet** [comment]
That's a half surprise to me. Some **linkers** are very picky, some are more permissive.
On Linux, Debian linker refuses some things RedHat linker is perfectly fine with.
So I guess the **linker** of Big Sur is even more pickier, and the OS linker is used regardless which compiler invokes it.

A wise man once said: "the more I think I understand linkers, the more I realize I do not understand them"

**Comment by fxcoudert** [comment]
I think I know why that could be. You have in many places code like this (here it's `opal/mca/pmix/pmix3x/pmix/config/libtool.m4`):

```
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
        10.0,*86*-darwin8*|10.0,*-darwin[[91]]*)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
        10.[[012]][[,.]]*)
          _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
        10.*)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
      esac
```

But with macOS Big Sur two things happened:
- macOS version went from 10.15 to 11.0
- darwin version went from `darwin19` to `darwin20`

So I'm thinking the wrong linker flags are being picked up.

**Comment by ggouaillardet** [comment]
That's a nice catch!
`libtool.m4` is automatically generated at `autogen.pl` time, and is then put into the tarball.
That means we should generate the tarball with autotools that support Big Sur.

Meanwhile, I suggest you run `autogen.pl --force` in the source directory before `configure` and see if it helps
(you need the `--force` flag when running `autogen.pl` from a dist tarball)

**Comment by fxcoudert** [comment]
Regenerating works, but only because we're using a patched libtool. Upstream hasn't yet applied this patch: https://lists.gnu.org/archive/html/libtool-patches/2020-06/msg00001.html

**Comment by jsquyres** [comment]
Ah crud.  Looks like we're going to need to apply that patch retroactively.  We might even need it across multiple of the Open MPI projects.  😢

**Comment by jsquyres** [comment]
@fxcoudert We're working on a PR to fix the issue. I cherry-picked the fix to a v4.1.x tarball -- could you try it and let me know if it works?

https://aws.open-mpi.org/~jsquyres/unofficial/openmpi-gitclone-v4.1.x-including-big-sur-libtool-fix.tar.bz2

(this link will likely disappear after this issue is closed)

**Comment by fxcoudert** [comment]
The test build is queued at https://github.com/Homebrew/homebrew-core/pull/65296
We will see if the 11.0 runner completes fine

**Comment by fxcoudert** [comment]
Build failure on 10.14: https://pipelines.actions.githubusercontent.com/revSbsLpzrFApLL6BmCvScWt72tRe3wYUv7fCdCtThtI5bydk7/_apis/pipelines/1/runs/82101/signedlogcontent/13?urlExpires=2020-11-20T18%3A25%3A50.3009816Z&urlSigningMethod=HMACV1&urlSignature=jEOyAMm%2F8iULB3l42X5QoxN2k%2BUDW0Wsf7iSHnllMYg%3D

Some occurrences of:

```
/bin/sh: command substitution: line 0: unexpected EOF while looking for matching `}'
```

and 

```
op_avx_functions.c:454:5: error: always_inline function '_mm512_loadu_si512' requires target feature 'avx512f', but would be inlined into function 'ompi_op_avx_2buff_max_int8_t_avx512' that is compiled without support for 'avx512f'
```

**Comment by jsquyres** [comment]
@ggouaillardet just merged the fix on master.  🎉 

@ggouaillardet Can you make PR's for v4.0.x and v4.1.x?  Thanks!

**Comment by bgoglin** [comment]
@ggouaillardet @jsquyres I am having a hard time trying to understand if this matters to hwloc (I am supposed to release hwloc 2.4rc1 today). I found some report that hwloc works fine on big sur, but we do not enable plugins by default in hwloc, could be related?

**Comment by fxcoudert** [comment]
@bgoglin I can confirm hwloc-2.3.0 builds fine from source on macOS 11.0 Big Sur. I can even confirm that it builds fine on macOS 11.0 with ARM-based processors (Apple Silicon).

**Comment by bgoglin** [comment]
Thanks!

**Comment by hjelmn** [comment]
Though on the M1 the output is a little confused:

```
/-----------------------------------------------------------------------------------------\
| Machine (3492MB total)                                                                  |
|                                                                                         |
| /---------------------------------------------------------------\  /------------------\ |
| | Package L#0                                                   |  | CoProc opencl0d0 | |
| |                                                               |  |                  | |
| | /-----------------------------------------------------------\ |  | 8 compute units  | |
| | | NUMANode L#0 P#0 (3492MB)                                 | |  |                  | |
| | \-----------------------------------------------------------/ |  | 10 GB            | |
| |                                                               |  \------------------/ |
| | /-------------\  /-------------\              /-------------\ |                       |
| | | L2 (4096KB) |  | L2 (4096KB) |  ++  ++  ++  | L2 (4096KB) | |                       |
| | \-------------/  \-------------/              \-------------/ |                       |
| |                                    8x total                   |                       |
| | /-------------\  /-------------\              /-------------\ |                       |
| | | L1d (64KB)  |  | L1d (64KB)  |              | L1d (64KB)  | |                       |
| | \-------------/  \-------------/              \-------------/ |                       |
| |                                                               |                       |
| | /-------------\  /-------------\              /-------------\ |                       |
| | | L1i (128KB) |  | L1i (128KB) |              | L1i (128KB) | |                       |
| | \-------------/  \-------------/              \-------------/ |                       |
| |                                                               |                       |
| | /------------\   /------------\               /------------\  |                       |
| | | Core L#0   |   | Core L#1   |               | Core L#7   |  |                       |
| | |            |   |            |               |            |  |                       |
| | | /--------\ |   | /--------\ |               | /--------\ |  |                       |
| | | | PU L#0 | |   | | PU L#1 | |               | | PU L#7 | |  |                       |
| | | |        | |   | |        | |               | |        | |  |                       |
| | | |  P#0   | |   | |  P#1   | |               | |  P#7   | |  |                       |
| | | \--------/ |   | \--------/ |               | \--------/ |  |                       |
| | \------------/   \------------/               \------------/  |                       |
| \---------------------------------------------------------------/                       |
\-----------------------------------------------------------------------------------------/
/-----------------------------------------------------------------------------------------\
| Host: Mac-mini.local                                                                    |
|                                                                                         |
| Date: Mon Nov 23 09:05:39 2020                                                          |
\-----------------------------------------------------------------------------------------/
```

**Comment by jsquyres** [comment]
Fix has been merged on master and v4.0.x and v4.1.x branches.

**Comment by chenrui333** [comment]
Same error seen in 4.1.0 release build.

```
op_avx_functions.c:454:5: error: always_inline function '_mm512_loadu_si512' requires target feature 'avx512f', but would be inlined into function 'ompi_op_avx_2buff_max_int8_t_avx512' that is compiled without support for 'avx512f'
    OP_AVX_FUNC(max, i, 8,    int8_t, max)
    ^
```

reported a separate issue, #8306
