### ISSUE TITLE
Master build failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by bwbarrett** [open-mpi/ompi#7676]
master is failing to build on Ubuntu 20.04.  I will look into what's going on, but wanted to cut a ticket so that I don't forget:

```
./configure --prefix=<path> && make
...
Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: internal
PMIx support: Internal
PRRTE: yes
Threading Package: pthreads
...
Making all in tools/prted
make[3]: Entering directory '/home/bbarrett/projects/open-mpi/ompi-clean/prrte/src/tools/prted'
  CC       prted.o
  GENERATE prted.1
prted.c: In function ‘main’:
prted.c:412:9: warning: ignoring return value of ‘pipe’, declared with attribute warn_unused_result [-Wunused-result]
  412 |         pipe(wait_pipe);
      |         ^~~~~~~~~~~~~~~
  CCLD     prted
/usr/bin/ld: prted.o: undefined reference to symbol 'hwloc_bitmap_iszero'
/usr/bin/ld: /lib/x86_64-linux-gnu/libhwloc.so.15: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:881: prted] Error 1
make[3]: Leaving directory '/home/bbarrett/projects/open-mpi/ompi-clean/prrte/src/tools/prted'
make[2]: *** [Makefile:1815: all-recursive] Error 1
make[2]: Leaving directory '/home/bbarrett/projects/open-mpi/ompi-clean/prrte/src'
make[1]: *** [Makefile:845: all-recursive] Error 1
make[1]: Leaving directory '/home/bbarrett/projects/open-mpi/ompi-clean/prrte'
make: *** [Makefile:1529: all-recursive] Error 1
```

**Comment by rhc54** [comment]
I suspect the issue is that you picked up an external HWLOC, but are trying to build with internal libevent and pmix. We only have PRRTE linked against libopen-pal, so if hwloc isn't in that library, PRRTE won't find the symbols. IIRC, if you select one of those three (hwloc, libevent, pmix) to be external, then they _all_ had to be external.

**Comment by bwbarrett** [comment]
The core problem is that as of Ubuntu 20.04, the linker has been modified so that if artifact (library or binary) A calls function B in library b, then A must add the -lb, even if it adds a -lc, where c depends on a.  In this case, prted is making hwloc calls, but depending on libopen-pal.so to pull in the hwloc dependency.

It looks like I've accidentally fixed this in my branch, so we don't have to do anything going forward.  I've also confirmed we did the right things on the 4.0 and 3.x branches, so this is master only.

**Comment by hppritcha** [comment]
I'm seeing similar behavior on my ubuntu vm, but with libevent.
No problem building prrte standalone:
```
/bin/bash ../../../libtool  --tag=CC   --mode=link gcc  -O3 -DNDEBUG -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing -mcx16 -pthread     -L/home/hpp/sessions_install/lib -o prte prte.o     ../../../src/libprrte.la -lm -lutil   -levent_core -levent_pthreads -lpmix -lhwloc
libtool: link: gcc -O3 -DNDEBUG -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing -mcx16 -pthread -o .libs/prte prte.o  -L/home/hpp/sessions_install/lib ../../../src/.libs/libprrte.so -lm -lutil -levent_core -levent_pthreads /home/hpp/sessions_install/lib/libpmix.so /home/hpp/sessions_install/lib/libhwloc.so -pthread -Wl,-rpath -Wl,/home/hpp/sessions_install/lib
make[2]: Leaving directory '/home/hpp/prrte/src/tools/prte'
```
built within OMPI:
```
/bin/bash ../../../libtool  --tag=CC   --mode=link gcc  -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread   -o prted prted.o /home/hpp/ompi2/opal/libopen-pal.la    ../../../src/libprrte.la -lm -lutil  
libtool: link: gcc -DNDEBUG -O3 -fvisibility=hidden -finline-functions -fno-strict-aliasing -mcx16 -pthread -o .libs/prted prted.o  /home/hpp/ompi2/opal/.libs/libopen-pal.so ../../../src/.libs/libprrte.so -lm -lutil -pthread -Wl,-rpath -Wl,/home/hpp/ompi2/test_install/lib
/usr/bin/ld: prted.o: undefined reference to symbol 'event_base_loop'
//usr/lib/x86_64-linux-gnu/libevent-2.1.so.6: error adding symbols: DSO missing from command line
```
I'm using Ubuntu 18.04

**Comment by gpaulsen** [comment]
Is this still and issue?

**Comment by jsquyres** [comment]
I just built master with Ubu 20.04 in a VM.  Looks like this has been fixed.  Closing.
