### ISSUE TITLE
No Infiniband transport on a ConnectX-3 cluster

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#5964]
I wanted to refresh OpenMPI on our ConnectX-3 based cluster, and ran into a lot of problems with IB support. We are running Mellanox OFED 4.4-2.0.7.0 on a well-aged Centos 6.9. First I tried to compile OpenMPI 3.1.2 _without_ HPCX, with only `openib`. That compiled fine, but running simple MPI applications reveals problems with IB:

```
$ mpirun ./mpitest
[compute-9-19][[47293,1],9][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Success
[...]
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   compute-9-13
  Local device: mlx4_0
--------------------------------------------------------------------------
```
I've checked and we see the same problems with older versions of OpenMPI, down to 2.0.1. The last version, which seems to be working with `openib` is 1.10.6. I do not know what causes the problem, and how long it's been there. The fact is that our default module for OpenMPI was v1.10.6, so it's possible that the error escaped our attention and was there for a long time. Could it be that it is triggered by new OFED versions?

I downloaded the newest HPCX 2.2 to see, if I can get it to work with yalla / mxm / ucx. UCX did manage to get through the configure stage. From `config.log`:

```
/cluster/software/VERSIONS/hpcx/hpcx-v2.2.0/ucx/lib/libuct.so.0: undefined reference to `ibv_cmd_modify_qp@IBVERBS_1.0'
collect2: error: ld returned 1 exit status
[...]
configure:322445: error: UCX support requested but not found.  Aborting
```

I turned off UCX and OpenMPI compiled fine. However, running with any of the yalla / mxm / hcoll components results in IB errors, e.g.:

```
[1540286451.312459] [compute-9-19:18182:0]      ib_dev.c:533  MXM  WARN  failed call to ibv_exp_use_priv_env(): Function not implemented
[1540286451.312465] [compute-9-19:18182:0]      ib_dev.c:544  MXM  ERROR ibv_query_device() returned 38: Function not implemented
```

or 

```
[compute-9-13.local:8236:6][bcol_ucx_p2p_component.c:481:hmca_bcol_ucx_p2p_init_query] UCXP2P failed to init ucx
[compute-9-13.local:08236] Error: coll_hcoll_module.c:311 - mca_coll_hcoll_comm_query() Hcol library init failed
[1540286474.435823] [compute-9-13:8233 :0]      ib_device.c:237  UCX  ERROR ibv_query_device() returned 38: No such file or directory
```

As a result, any recent version of OpenMPI is only working with tcp transport.

I'd appreciate any help with this.

Thanks!

Marcin

**Comment by yosefe** [comment]
@angainor what is the output of `rpm -q libibverbs` and `nm -D /usr/lib64/libibverbs.so.1|grep cmd_modify_qp`?
it's possible there is something wrong with MLNX_OFED installation

**Comment by angainor** [comment]
@yosefe Thanks for a quick answer. Here are the results:

```
compute-9-13 ~/mpitest $ rpm -q libibverbs
libibverbs-43mlnx1-1.44207.x86_64

compute-9-13 ~/mpitest $ nm -D /usr/lib64/libibverbs.so.1|grep cmd_modify_qp
0000000000008c40 T ibv_cmd_modify_qp
0000000000008ab0 T ibv_cmd_modify_qp_ex
```

I see that we have a different OFED on our login nodes, but I ran a single-node test now, on the above compute node, and still get the errors:

```
mpirun -np 1 ./mpitest
--------------------------------------------------------------------------
Initialization of MXM library failed.

  Error: Input/output error

--------------------------------------------------------------------------
[1540291122.375282] [compute-9-13:10870:0]      ib_dev.c:533  MXM  WARN  failed call to ibv_exp_use_priv_env(): Function not implemented
```

**Comment by yosefe** [comment]
@angainor can you try to run basic IB tests on the compute node? e.g `ibv_devinfo` and `ib_send_lat`?
Also, what is the content of `/cluster/software/VERSIONS/hpcx/hpcx-v2.2.0/VERSION`?

**Comment by angainor** [comment]
`ib_send_lat` shows some errors (see below)

```
compute-9-13 ~/mpitest $ cat /cluster/software/VERSIONS/hpcx/hpcx-v2.2.0/VERSION
HPCX v2.2.0
kickstart.git  (d13c9f2)
libhcoll-v4.1  4.1.2365 (22db7d1)
mxm-v3.7  3.7.3111 (8b0b99e)
ompi  gitclone (cb9825e)
sharp-v1.7  1.7.1 (7c14dc0)
ucx-v1.4.x  1.4.0 (3439b38)
distro redhat6.9
ofed   MLNX_OFED_LINUX-4.4-1.0.0.0
buildnumber   659
```

```
compute-9-13 ~/mpitest $ ibv_devinfo 
hca_id:	mlx4_0
	transport:			InfiniBand (0)
	fw_ver:				2.35.5100
	node_guid:			0025:90ff:ff17:4880
	sys_image_guid:			0025:90ff:ff17:4883
	vendor_id:			0x02c9
	vendor_part_id:			4099
	hw_ver:				0x1
	board_id:			SM_2191000001000
	phys_port_cnt:			1
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			22
			port_lid:		381
			port_lmc:		0x00
			link_layer:		InfiniBand
```

```
compute-9-13 ~/mpitest $ ib_send_lat c9-14
Couldn't get ibv_exp_post_send pointer
Couldn't get device attributes
---------------------------------------------------------------------------------------
                    Send Latency Test
 Dual-port       : OFF		Device         : mlx4_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 TX depth        : 1
 Mtu             : 2048[B]
 Link type       : IB
 Max inline data : 236[B]
 rdma_cm QPs	 : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x17d QPN 0x39ace PSN 0x7aa206
 remote address: LID 0x183 QPN 0x1b1de PSN 0x90e75a
---------------------------------------------------------------------------------------
 #bytes #iterations    t_min[usec]    t_max[usec]  t_typical[usec]    t_avg[usec]    t_stdev[usec]   99% percentile[usec]   99.9% percentile[usec] 
 2       1000          1.20           33.45        1.26     	       1.36        	1.33   		2.11    		33.45  
---------------------------------------------------------------------------------------
```

**Comment by yosefe** [comment]
@angainor what is the output of `ofed_info` and `cat /proc/kallsyms |grep uverbs_exp`?

**Comment by angainor** [comment]
[ofed_info.txt](https://github.com/open-mpi/ompi/files/2505843/ofed_info.txt)


```
compute-9-13 ~/mpitest $ cat /proc/kallsyms |grep uverbs_exp
0000000000000000 d uverbs_exp_cmd_table	[ib_uverbs]
0000000000000000 r __ksymtab_ib_uverbs_exp_query_mkey	[ib_uverbs]
0000000000000000 r __kstrtab_ib_uverbs_exp_query_mkey	[ib_uverbs]
0000000000000000 r __kcrctab_ib_uverbs_exp_query_mkey	[ib_uverbs]
0000000000000000 t uverbs_exp_free_dct	[ib_uverbs]
0000000000000000 t uverbs_exp_free_dm	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_destroy_dct	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_set_context_attr	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_query_device	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_modify_cq	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_srq_resp	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_query_dct	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_destroy_wq	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_free_dm	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_destroy_rwq_ind_table	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_rwq_ind_table	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_dct	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_flow	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_reg_mr	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_alloc_dm	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_get_unmapped_area	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_wq	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_mr	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_arm_dct	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_qp	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_modify_qp	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_cq	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_create_srq	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_modify_wq	[ib_uverbs]
0000000000000000 t ib_uverbs_exp_ioctl	[ib_uverbs]
0000000000000000 T ib_uverbs_exp_query_mkey	[ib_uverbs]
```

**Comment by yosefe** [comment]
@angainor ofed_info and kallsyms look right, and i don't see such error on my ConnectX3/MOFED 4.5-2.0.7.0/Redhat 6.5 system.
Any chance you can try to reinstall MLNX_OFED on `compute-9-13` and restart openibd service, and check if you still see the error from ib_send_lat?

**Comment by angainor** [comment]
@yosefe Thanks a lot for your effort. There might well be something wrong with our OFED installation, but I don't see what yet. I've removed all mlnx rpms, and installed `mlnx-ofed-basic` - that worked. Then, I installed `perftest` to run the latency test:

```
# yum install perftest
Setting up Install Process
Resolving Dependencies
There are unfinished transactions remaining. You might consider running yum-complete-transaction first to finish them.
The program yum-complete-transaction is found in the yum-utils package.
--> Running transaction check
---> Package perftest.x86_64 0:4.4-0.2.g4942ab6.44207 will be installed
--> Processing Dependency: libibumad.so.3(IBUMAD_1.0)(64bit) for package: perftest-4.4-0.2.g4942ab6.44207.x86_64
--> Processing Dependency: libibumad.so.3()(64bit) for package: perftest-4.4-0.2.g4942ab6.44207.x86_64
--> Running transaction check
---> Package libibumad.x86_64 0:43mlnx1-1.44207 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================
 Package                                       Arch                                       Version                                                       Repository                                     Size
============================================================================================================================================================================================================
Installing:
 perftest                                      x86_64                                     4.4-0.2.g4942ab6.44207                                        Rocks-6.2                                     210 k
Installing for dependencies:
 libibumad                                     x86_64                                     43mlnx1-1.44207                                               Rocks-6.2                                      16 k

Transaction Summary
============================================================================================================================================================================================================
Install       2 Package(s)
```

This worked, but I get the same error with `ib_send_lat` as before. I rebooted the compute node after packages were re-installed, just in case.

However, when I tried to install `mlnx-ofed-hpc`, I got a lot of problems with the `libibumad` package.
[libibumad.txt](https://github.com/open-mpi/ompi/files/2506982/libibumad.txt)

It seems that some packages are unhappy with the RPM we have in our repo. There are the following `libibumad` packages there:

```
libibumad-43.1.1.MLNX20180612.87b4d9b-0.1.44207.i686.rpm
libibumad-43mlnx1-1.44207.x86_64.rpm
libibumad-devel-43.1.1.MLNX20180612.87b4d9b-0.1.44207.i686.rpm
libibumad-devel-43.1.1.MLNX20180612.87b4d9b-0.1.44207.x86_64.rpm
libibumad-static-43.1.1.MLNX20180612.87b4d9b-0.1.44207.i686.rpm
libibumad-static-43.1.1.MLNX20180612.87b4d9b-0.1.44207.x86_64.rpm
```

Does anything strike you as wrong? At least the name should be different, it seems.

**Comment by angainor** [comment]
@yosefe I think to double-check we will rebuild the entire RPM roll of mellanox ofed. Maybe something went wrong during the building process (kernel version?). I will double-check with new RPMs and will get back after running new tests, hopefully tomorrow. Thanks for the hints!

**Comment by angainor** [comment]
@yosefe Yes, this is what I meant - I think `mlnxofedinstall` rebuilds the kernel modules. Anyway, we've done that now and tested one compute node with the new RPMs - all seems to work fine now, or at least I do not get any of the previous errors. So you were right - it was a problem with our MOFED installation. Thanks a lot for your help!

**Comment by angainor** [comment]
@yosefe I was a bit quick in my enthusiasm :( I've rebuilt ompi 3.1.2 now to add UCX support, which was previously gone. In the new compilation I get an error during `openib` initialization:

```
compute-3-1 ~/mpitest $ mpirun -np 2 -mca pml ^yalla -mca mtl ^mxm -mca btl openib,self ./mpitest
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0xffffffffffffffff valid_mask = 0x1)
[compute-3-1][[24454,1],1][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Invalid argument
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0xffffffffffffffff valid_mask = 0x1)
[compute-3-1][[24454,1],0][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Invalid argument
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   compute-3-1
  Local device: mlx4_0
--------------------------------------------------------------------------
```
uff.. Does anything come to your head? We've never had such problems before. Is it possible that there still are some RPM problems with our OFED?

**Comment by angainor** [comment]
OK, I see now that this time it is a know problem: #5810
