### PR TITLE
configury: String OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR

### LINKED ISSUE #9494: master/v5.0.x: Compile error with clang and armclang
Thank you for taking the time to submit an issue!

## Background information

Building latest ompi out of gtihub, get error with armclang 21.1

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

github @ 4b50f265e6cbe31d744af2a4e47a28d73ac5e4d0 (master)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```
 409d89fd2c6ad47e6cab4d4f18e72dd3e0af2e70 3rd-party/openpmix (v1.1.3-3138-g409d89fd)
 8622c287399f3a22102b998aee098d97a621bdbe 3rd-party/prrte (psrvr-v2.0.0rc1-4018-g8622c28739)
```

### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 8.1.1911
* Computer hardware: aarch64
* Network type: IB

-----------------------------

## Details of the problem

```
make[2]: Entering directory '/autofs/nccs-svm1_envoy_od/arcurtis/src/openmpi/build/ompi/tools/ompi_info'
depbase=`echo param.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
armclang -DHAVE_CONFIG_H -I. -I../../../../openmpi-git/ompi/tools/ompi_info -I../../../opal/include -I../../../ompi/include -I../../../oshmem/include -I../../../ompi/mpiext/cuda/c   -iquote../../../../openmpi-git -iquote../../.. -iquote../../../../openmpi-git/opal/include -iquote../../../../openmpi-git/ompi/include -iquote../../../../openmpi-git/oshmem/include  -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/libevent-2.1.12-stable -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/libevent-2.1.12-stable/include -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/hwloc-2.4.0/include -I/ccsopen/home/arcurtis/src/openmpi/openmpi-git/3rd-party/hwloc-2.4.0/include -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/openpmix/include -I/ccsopen/home/arcurtis/src/openmpi/openmpi-git/3rd-party/openpmix/include -DOPAL_CONFIGURE_USER="\"arcurtis\"" -DOPAL_CONFIGURE_HOST="\"wombat-login2\"" -DOPAL_CONFIGURE_DATE="\"Thu Oct  7 19:26:30 UTC 2021\"" -DOMPI_BUILD_USER="\"$USER\"" -DOMPI_BUILD_HOST="\"${HOSTNAME:-`(hostname || uname -n) | sed 1q`}\"" -DOMPI_BUILD_DATE="\"`../../../../openmpi-git/config/getdate.sh`\"" -DOMPI_BUILD_CFLAGS="\"-O3 -DNDEBUG -finline-functions\"" -DOMPI_BUILD_CPPFLAGS="\"-iquote../../../../openmpi-git -iquote../../.. -iquote../../../../openmpi-git/opal/include -iquote../../../../openmpi-git/ompi/include -iquote../../../../openmpi-git/oshmem/include  -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/libevent-2.1.12-stable -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/libevent-2.1.12-stable/include -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/hwloc-2.4.0/include -I/ccsopen/home/arcurtis/src/openmpi/openmpi-git/3rd-party/hwloc-2.4.0/include -I/ccsopen/home/arcurtis/src/openmpi/build/3rd-party/openpmix/include -I/ccsopen/home/arcurtis/src/openmpi/openmpi-git/3rd-party/openpmix/include\"" -DOMPI_BUILD_CXXFLAGS="\"-DNDEBUG \"" -DOMPI_BUILD_CXXCPPFLAGS="\"@CXXCPPFLAGS@\"" -DOMPI_BUILD_FFLAGS="\"\"" -DOMPI_BUILD_FCFLAGS="\"\"" -DOMPI_BUILD_LDFLAGS="\"\"" -DOMPI_BUILD_LIBS="\"-lpthread -lrt -lutil \"" -DOPAL_CC_ABSOLUTE="\"/sw/wombat/ARM_Compiler/20.3/arm-linux-compiler-20.3_Generic-AArch64_RHEL-8_aarch64-linux/bin/armclang\"" -DOMPI_CXX_ABSOLUTE="\"/sw/wombat/ARM_Compiler/20.3/arm-linux-compiler-20.3_Generic-AArch64_RHEL-8_aarch64-linux/bin/armclang++\"" -O3 -DNDEBUG -finline-functions -MT param.o -MD -MP -MF $depbase.Tpo -c -o param.o ../../../../openmpi-git/ompi/tools/ompi_info/param.c &&\
mv -f $depbase.Tpo $depbase.Po
../../../../openmpi-git/ompi/tools/ompi_info/param.c:341:80: error: expected ')'
                  PLATFORM_STRINGIFY(OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR));
                                                                               ^
../../../../openmpi-git/ompi/tools/ompi_info/param.c:340:18: note: to match this '('
    opal_info_out("C compiler version", "compiler:c:version",
                 ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by kawashima-fj**
Fixes #9494

Before this change, the `OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR` macro is defined as a non-string character sequence (no enclosing double quotes) in `opal_config.h`.

This is problematic if it contains `//` because it is treated as a start of comment. Also, if it contains `(` or `)`, `PLATFORM_STRINGIFY(OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR)` will result in a compilation error. Probably this is the case of the issue #9494 because some builds of Clang/LLVM 9 and 10 set `__clang_version__` like below.

```
clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)
```

This commit changes `OPAL_BUILD_PLATFORM_COMPILER_VERSION_STR` to a string (enclosing with double quotes).

I think this is a proper approach because it is consistent with the `PLATFORM_COMPILER_VERSION_STR` macro, where `opal/include/opal/opal_portable_platform_real.h` defines it as a string.

Probably regression by d6bfdf2ace.

Need PR to v5.0.x branch.

### CODE REVIEW

**Comment by bwbarrett** [comment]
I think `AS_ESCAPE` does what you're looking for, with a lot less mess.

However, I think even that's the wrong solution.  We need to define `OPAL_BUILD_PLATFORM_COMPILER_FAMILYID` and `OPAL_BUILD_PLATFORM_COMPILER_VERSION` (the integer defines) so that we can do the compiler change check in mpi.h at application build time.  That means we need to `AC_DEFINE_UNQUOTED` those two parameters so that they get substituted into mpi.h.

However, we don't actually need to `AC_DEFINE_UNQUOTED` the string versions.  The only places we use them can include opal_portable_platform.h directly and use the `PLATFORM_*` defines, which are just pre-processor defined to the compiler defines, which can be passed through `PLATFORM_STRINGIFY`.  If we can just not touch the string versions of the macros, I think our lives will generally be much better.

I'll try to work on a patch to do this today, but may run out of time.
