### PR TITLE
v2.0.x ppc fixes

### PR DESCRIPTION
**Pull request by hjelmn**
Assembly workarounds for PGI.

### CODE REVIEW

**Comment by jjhursey** [comment]
Similar failure on this PR as in PR #2177:

```shell
shell$ uname -m
ppc64le
shell$ pgcc --version

pgcc 16.9-beta linuxpower target on Linuxpower 
The Portland Group - PGI Compilers and Tools
Copyright (c) 2016, NVIDIA CORPORATION.  All rights reserved.
shell$ ./configure --without-x CC=pgcc CXX=pgc++ FC=pgfortran
...
shell$ make
...
make[2]: Entering directory `/tmp/jjh-core/ompi-test/ompi-v2.0.x-ppc/opal/tools/wrappers'
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_sc_64'
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_add_64'
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_ll_64'
../../../opal/.libs/libopen-pal.so: undefined reference to `opal_atomic_swap_64'
make[2]: *** [opal_wrapper] Error 2
make[2]: Leaving directory `/tmp/jjh-core/ompi-test/ompi-v2.0.x-ppc/opal/tools/wrappers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/jjh-core/ompi-test/ompi-v2.0.x-ppc/opal'
make: *** [all-recursive] Error 1
```

**Comment by hjelmn** [comment]
Opps, I know why it doesn't work. It isn't using the inline assembly and we do not have the appropriate asm file for this to work in 2.0.x. 2.1.x will re-enable inline assembly for PGI but it will be a hard sell for 2.0.x. Will have to talk with Jeff and Howard about that.

**Comment by hjelmn** [comment]
@hppritcha Right now PGI on PPC does not work at all with 2.0.x. In order for it to work it looks like we need to re-enable inline asm for PGI. @sjeaugey Is that ok for 2.0.x?

It may break Open MPI with PGI versions older than 10.8. I may be able to add work arounds for the bugs inversions from when inline assembly is supported to 10.8 as I have with PPC for 16.x. Gasnet has all the relevant bugs documented.

**Comment by cparrott73** [comment]
Hi @hjelmn - I work for NVIDIA/PGI and do testing of Open MPI on POWER here.  As far as we're concerned, we would be fine with enabling inline assembly support for PGI on Open MPI.  This would enable Open MPI to compile as written with PGI on POWER.  Let me know if you need any additional information from us.

**Comment by jjhursey** [comment]
The updated branch builds and passes some basic testing (`make check` and `ring_c`).
Thanks!

I'll add my review approval, and I'll let the author decide if it needs to be updated based on the comment about older PGI compilers.

**Comment by jsquyres** [comment]
@hppritcha Good to go.
