### PR TITLE
Pr/sharedfp append fix v2.x

### PR DESCRIPTION
**Pull request by edgargabriel**
this is the second part of the sharedfp append fix for the v2.x branch. For the 2.0.x branch, all four commits were merged at the same time.

### CODE REVIEW

**Comment by edgargabriel** [comment]
the failure in LANL-disable-dlopen does not seem related to this pr. 

--snip--
+ mpicc -o hello_c.x hello_c.c
/home/hppritcha/jenkins/workspace/ompi_master_pr_disable_dlopen/ompi_install/lib64/libmpi.so: undefined reference to `mca_base_var_enum_create_flag'
collect2: error: ld returned 1 exit status
Build step 'Execute shell' marked build as failure
--snip--

**Comment by hppritcha** [comment]
and try this again:
bot:lanl:retest

**Comment by edgargabriel** [comment]
@jsquyres  since you reviewed the euqivalent for the 2.0.2 release, would you mind doing the same for the 2.1 release?

**Comment by jsquyres** [comment]
@hppritcha Good to go.
