### ISSUE TITLE
Build failure with --with-hwloc=external

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi#2616]
If I try to build the Fedora openmpi package with --with-hwloc=external I end up with:
```
In file included from ../../opal/mca/hwloc/hwloc.h:131:0,
                 from proc.h:21,
                 from proc.c:19:
../../opal/mca/hwloc/external/external.h:20:35: fatal error: /include/hwloc.h: No such file or directory
 #include MCA_hwloc_external_header
                                   ^
compilation terminated.
```
Full logs - https://kojipkgs.fedoraproject.org//work/tasks/5738/17005738/build.log
It does work with --with-hwloc=/usr, but I noticed a post on the mailing list suggesting that that was bad practice.

**Comment by ggouaillardet** [comment]
@opoplawski thanks for the report, i will be pushing a fix shortly

**Comment by opoplawski** [comment]
Looks good here.  Thanks.

**Comment by opoplawski** [comment]
So, it worked okay with the #2618 patch, but now with 2.0.2rc2 I get lots of errors:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../opal/include -I../../../ompi/include -I../../../oshmem/include -I../../../opal/mca/hwloc/hwloc1112/hwloc/include/private/autogen -I../../../opal/mca/hwloc/hwloc1112/hwloc/include/hwloc/autogen -I../../../ompi/mpiext/cuda/c -I../../../opal/include -I../../.. -I../../../orte/include -I/builddir/build/BUILD/openmpi-2.0.2rc2/opal/mca/event/libevent2022/libevent -I/builddir/build/BUILD/openmpi-2.0.2rc2/opal/mca/event/libevent2022/libevent/include -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -finline-functions -fno-strict-aliasing -mcx16 -pthread -MT base/hwloc_base_dt.lo -MD -MP -MF base/.deps/hwloc_base_dt.Tpo -c base/hwloc_base_dt.c  -fPIC -DPIC -o base/.libs/hwloc_base_dt.o
In file included from ../../../opal/mca/hwloc/base/base.h:18:0,
                 from base/hwloc_base_dt.c:15:
../../../opal/mca/hwloc/hwloc.h:142:5: error: unknown type name 'hwloc_cpuset_t'
     hwloc_cpuset_t available;
     ^~~~~~~~~~~~~~
../../../opal/mca/hwloc/hwloc.h:152:5: error: unknown type name 'hwloc_obj_type_t'
     hwloc_obj_type_t type;
     ^~~~~~~~~~~~~~~~
../../../opal/mca/hwloc/hwloc.h:162:5: error: unknown type name 'hwloc_cpuset_t'
     hwloc_cpuset_t available;
     ^~~~~~~~~~~~~~
../../../opal/mca/hwloc/hwloc.h:214:22: error: unknown type name 'hwloc_topology_t'
 OPAL_DECLSPEC extern hwloc_topology_t opal_hwloc_topology;
                      ^~~~~~~~~~~~~~~~
```
and so on.  Full logs here: https://kojipkgs.fedoraproject.org//work/tasks/5380/17085380/build.log

**Comment by jsquyres** [comment]
Do you have a version of hwloc that is too old?

**Comment by opoplawski** [comment]
No, just updated it to 1.11.5 to be sure of that.

**Comment by ggouaillardet** [comment]
there are way too much include directories in the command line, and the point of the patch was mainly to get rid of ```-I.```
i will have a look from now

**Comment by ggouaillardet** [comment]
@jsquyres this is from the generated ```opal/mca/hwloc/Makefile```
```
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
        $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
```

so what we really need here is to override ```$(DEFAULT_INCLUDES)``` and not add some more stuff to ```$(AM_CPPFLAGS)```

makes sense ?

the inline patch restore part of my initial patch
```patch
diff --git a/opal/mca/hwloc/Makefile.am b/opal/mca/hwloc/Makefile.am
index c5340da..2aa843b 100644
--- a/opal/mca/hwloc/Makefile.am
+++ b/opal/mca/hwloc/Makefile.am
@@ -10,9 +10,9 @@
 #
 
 # We do not want -I$(srcdir) in AM_CPPFLAGS, or there can be a
-# conflict between system hwloc.h and opal/mca/hwloc/hwloc.h.  So just
-# set only what we need to AM_CPPFLAGS.
-AM_CPPFLAGS = -I$(top_builddir)/opal/include
+# conflict between system hwloc.h and opal/mca/hwloc/hwloc.h.
+# So override DEFAULT_INCLUDES and only what is required
+DEFAULT_INCLUDES = -I$(top_builddir)/opal/include
 
 # main library setup
 noinst_LTLIBRARIES = libmca_hwloc.la
```

**Comment by jsquyres** [comment]
Odd.  I see that `INCLUDES` is deprecated in favor of `AM_CPPFLAGS`, but I do not see mention of `DEFAULT_INCLUDES` in the latest Automake docs at all.  I *do* see a *single* offhand reference to `DEFAULT_INCLUDES` in *older* Automake docs, though.

Is `DEFAULT_INCLUDES` really what we should be updating?

**Comment by jsquyres** [comment]
@opoplawski I'm looking into this issue.  One thing I note in the full logs is right up near the beginning of configure:

```
./configure: line 5711: hostname: command not found
```

Might want to add an RPM dependency for the RPM containing `hostname`...?

-----

@ggouaillardet I see the problem with `--with-hwloc=external`.  You won't hit this situation unless you have an hwloc installed in a default compiler/linker location (e.g., `/usr`), and you use `--with-hwloc=external`.  I.e., it's a different case than `--with-hwloc=DIR`.

The problem is:

1. `opal/mca/hwloc/hwloc.h` includes `MCA_hwloc_IMPLEMENTATION_HEADER`, which is `"opal/mca/hwloc/external/external.h"`
1. `external.h` includes `MCA_hwloc_external_header`, which is `"hwloc.h"`
1. Unfortunately, when we are building in the `opal/mca/hwloc` dir, there is a `hwloc.h` in the pwd.
1. We also have a `-I.` in the compile line.
1. The preprocessor therefore picks up `./hwloc.h` instead of the external/system `hwloc.h`.
1. Hence, all the hwloc symbols and types are undefined.

This `-I.` comes from `DEFAULT_INCLUDES`, which may well be what @ggouaillardet was trying to say in the first place.  😄 

Note: I'm 99.99% sure that didn't put `-I.` in `DEFAULT_INCLUDES` -- it was put there by Automake.

I'm not sure what the Right approach is to fix this issue.  I see a few options:

1. Rename `opal/mca/hwloc/hwloc.h` to something else.
   * We'll need to s/hwloc.h/hwloc-whatever.h/ throughout the code base, but that's not a big deal.
   * There may be other side effects, thought -- I'm pretty sure the MCA infrastructure *requires* a header file with the same name as the framework.  That might be difficult to work around.
1. Edit `DEFAULT_INCLUDES` so that it does not contain `-I.`, either directly or indirectly.  This might be what we have to do, but it sure is ugly -- it's undocumented, which, to me, makes it sound like an internal variable in Automake.
1. Add some kind of special case for handling building in the `opal/mca/hwloc` directory in the `.h` files.

Suggestions?

**Comment by jsquyres** [comment]
@opoplawski I should note that using `--with-hwloc=/usr` is likely a Good Enough workaround for now.  We definitely need to fix this issue, but that should get you building for now (and possibly for the v2.0.2 release).

**Comment by opoplawski** [comment]
Yeah, I've used --with-hwloc=/usr for ages now, so that's no problem.  The hostname thing can be ignored.

**Comment by jsquyres** [comment]
@ggouaillardet @artpol84 Still open for suggestions on how to solve this one (per https://github.com/open-mpi/ompi/issues/2616#issuecomment-270219658).  😄

**Comment by artpol84** [comment]
```
I'm not sure what the Right approach is to fix this issue. I see a few options:

1. Rename opal/mca/hwloc/hwloc.h to something else.
We'll need to s/hwloc.h/hwloc-whatever.h/ throughout the code base, but that's not a big deal.
There may be other side effects, though -- I'm pretty sure the MCA infrastructure requires a header file with the same name as the framework. That might be difficult to work around.
2. Edit DEFAULT_INCLUDES so that it does not contain -I., either directly or indirectly. This might be what we have to do, but it sure is ugly -- it's undocumented, which, to me, makes it sound like an internal variable in Automake.
3. Add some kind of special case for handling building in the opal/mca/hwloc directory in the .h files.
```

+1 for # 1

**Comment by ggouaillardet** [comment]
#1 looks like the best approach to me (though maybe a bit painful ...)
i do not mind taking a crack at it though, but before that, we should agree on how to rename the ```hwloc``` framework. i previously suggested ```hwtopo```, but remain open to new ideas

**Comment by ggouaillardet** [comment]
```hw``` is an other (and simpler) option

**Comment by jsquyres** [comment]
@ggouaillardet and I came up with competing solutions overnight.  😄 

I think I figured out overnight how to rename `opal/mca/hwloc/hwloc.h` without *too* much trouble -- see #2955.

**Comment by jsquyres** [comment]
@rhc54 Did you mean to close this issue?

**Comment by rhc54** [comment]
No, it was an update into a related repo - another "git-ism" ☹️
