### PR TITLE
v2.0.x: --with-hwloc=external fix

### LINKED ISSUE #2616: Build failure with --with-hwloc=external
If I try to build the Fedora openmpi package with --with-hwloc=external I end up with:
```
In file included from ../../opal/mca/hwloc/hwloc.h:131:0,
                 from proc.h:21,
                 from proc.c:19:
../../opal/mca/hwloc/external/external.h:20:35: fatal error: /include/hwloc.h: No such file or directory
 #include MCA_hwloc_external_header
                                   ^
compilation terminated.
```
Full logs - https://kojipkgs.fedoraproject.org//work/tasks/5738/17005738/build.log
It does work with --with-hwloc=/usr, but I noticed a post on the mailing list suggesting that that was bad practice.

### PR DESCRIPTION
**Pull request by jsquyres**
Fixes #2616 for v2.0.x.  Thanks to @opoplawski for reporting.

### CODE REVIEW

**Comment by hppritcha** [comment]
@ggouaillardet could you please review?
