### ISSUE TITLE
UCT BTL fails to compile using UCX 1.7.0

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#7128]
The UCT BTL in both master and v4.0.x fail to compile against UCX 1.7.0 rc1.
```
  CC       btl_uct_tl.lo
In file included from btl_uct_device_context.h:16:0,
                 from btl_uct_endpoint.c:17:
btl_uct_rdma.h: In function 'mca_btl_uct_get_rkey':
btl_uct_rdma.h:61:5: error: too few arguments to function 'uct_rkey_unpack'
     ucs_status = uct_rkey_unpack ((void *) remote_handle, rkey);
     ^
In file included from btl_uct_device_context.h:16:0,
                 from btl_uct_rdma.c:12:
btl_uct_rdma.h: In function 'mca_btl_uct_get_rkey':
In file included from btl_uct_device_context.h:16:0,
                 from btl_uct_amo.c:12:
btl_uct_rdma.h: In function 'mca_btl_uct_get_rkey':
In file included from btl_uct_device_context.h:16:0,
                 from btl_uct_component.c:43:
btl_uct_rdma.h: In function 'mca_btl_uct_get_rkey':
btl_uct_rdma.h:61:5: error: too few arguments to function 'uct_rkey_unpack'
     ucs_status = uct_rkey_unpack ((void *) remote_handle, rkey);
     ^
btl_uct_rdma.h:61:5: error: too few arguments to function 'uct_rkey_unpack'
     ucs_status = uct_rkey_unpack ((void *) remote_handle, rkey);
     ^
btl_uct_rdma.h:61:5: error: too few arguments to function 'uct_rkey_unpack'
     ucs_status = uct_rkey_unpack ((void *) remote_handle, rkey);
     ^
In file included from btl_uct.h:41:0,
                 from btl_uct_endpoint.c:15:
/users/hpritchard/ucx_testing//ucx-1.7.0//test_install/include/uct/api/uct.h:2142:14: note: declared here
 ucs_status_t uct_rkey_unpack(uct_component_h component, const void *rkey_buffer,
              ^
In file included from btl_uct_device_context.h:16:0,
                 from btl_uct_endpoint.c:17:
btl_uct_rdma.h: In function 'mca_btl_uct_rkey_release':
btl_uct_rdma.h:72:5: warning: passing argument 1 of 'uct_rkey_release' from incompatible pointer type [enabled by default]
     uct_rkey_release (rkey);
     ^
```
This is master including the commits from #7016.

Here's the current UCT BTL build situation:

| OMPI Version |UCX 1.6|UCX 1.7|UCX master|
| -------------------------- |:-:|:-:|:-:|
| `MASTER`              |✓ |:x:|✓ |
| `4.0.x`                |✓ |:x:|:x:|

**Comment by hppritcha** [comment]
we need this resolved for 4.0.x branch as not being able to build against UCX 1.7.x may impact ability to get UCX updates into certain linux distros.

**Comment by gpaulsen** [comment]
Lets talk on Tuesday about this.

**Comment by hjelmn** [comment]
I can resolve the 1.7 build failure. More than a little disappointed that the API freeze agreement was broken.

**Comment by jsquyres** [comment]
@hjelmn Thanks!  We'll still need version checking in the configury, though (because otherwise, we could be in this position *again* in the future 😦).

**Comment by hjelmn** [comment]
Not sure I agree. It will just silently fail to build when I want to see an error message to indicate that UCX (again) decided to change an external API.

**Comment by hjelmn** [comment]
And really this comes down to a failure of communication. This sort of issue can be fixed in ~5 mins but I never get a message about the break until it comes down to "lets just no-build btl/uct".

**Comment by hjelmn** [comment]
And really the only reason I see anything ATM is because @jsquyres accidentally deleted the dev groups. Reset all my alert preferences :rofl:. If there is a build failure for btl/uct please *always* tag me.

**Comment by jsquyres** [comment]
@hjelmn No, it will not silently fail -- that's the problem.  If UCX changes their API, we can be in the following situation (which has happened twice, BTW):

1. Open MPI version ABC compiles/works fine with UCX version XYZ.
1. UCX comes out with version (XYZ+1) and changes their API.
1. Open MPI version ABC passes `configure` and decides to build UCX, but then later _fails to compile_.

So we need to either:

* Check every single UCX API in `configure.m4` (because any of them can apparently change between UCX releases), or
* Put in UCX version checking in `configure.m4`.

Either is fine with me.  I'm tired of getting blamed for UCX changing their API.  ☹️

**Comment by hjelmn** [comment]
So, you want to fail configure? That would be ok with me. What I don't want is silently add btl-uct to the mca no build. UCX really should be blamed because they are changing an external API in **every** release now. I talked to them last December and they told me that was not going to happen. They said there were a couple of things they needed to update (which is fine) but then it would be stabilized. It has been a year and that has not happened.

**Comment by hjelmn** [comment]
I see the misunderstanding. With the check it will just silently fail btl/uct. That is what I do not want.

**Comment by hjelmn** [comment]
Fixed. The issue was that at the time I last tested the API break was not cherry-picked into v1.7.x.

**Comment by yosefe** [comment]
> So, you want to fail configure? That would be ok with me. What I don't want is silently add btl-uct to the mca no build. UCX really should be blamed because they are changing an external API in **every** release now. I talked to them last December and they told me that was not going to happen. They said there were a couple of things they needed to update (which is fine) but then it would be stabilized. It has been a year and that has not happened.

@hjelmn @jsquyres UCX has a stable high-level API - UCP - which is used by multiple OMPI components (and other MPI libs) and it doesn't change. The API used by Nathan's component is similar in some sense to BTL API. It's an unstable low-level API, intended for research/preview. The decision of upstreaming OMPI component using such API had its risks.

We talked about stabilizing UCT API a year ago, and we did make progress in that direction, but making it stable too early would make it very hard (or even impossible) to add some features and optimizations to UCX, so it hasn't happened yet. 

IMHO having an upper bound on UCX version for btl/uct is a good approach. we can always extend this upper bound after making adjustments, if needed, in btl/uct code.

**Comment by jsquyres** [comment]
See #7144 and #7142

**Comment by jsquyres** [comment]
Also see https://github.com/open-mpi/ompi/pull/7140#issuecomment-550449194.

**Comment by hppritcha** [comment]
resolved via #7152
