### ISSUE TITLE
Recent hwloc base change breaks external hwloc <= v2.0.x

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7362]
PR #7201 causes compile errors on master when compiling with older versions of hwloc (older than v2.0.x).

Open MPI master still supports hwloc >= v1.5.x.  Are we changing this to be >= v2.0.x?

Specifically, when I try compiling Open MPI master HEAD with an external installation of 1.5.1, I get the following compile error:

```
make[1]: Entering directory `/home/jsquyres/git/ompi/opal/mca/hwloc'
  CC       base/hwloc_base_util.lo
base/hwloc_base_util.c: In function ‘opal_hwloc_base_find_coprocessors’:
base/hwloc_base_util.c:1393:12: warning: unused variable ‘cps’ [-Wunused-variable]
     char **cps = NULL;
            ^~~
base/hwloc_base_util.c:1392:14: warning: unused variable ‘i’ [-Wunused-variable]
     unsigned i;
              ^
base/hwloc_base_util.c:1391:17: warning: unused variable ‘osdev’ [-Wunused-variable]
     hwloc_obj_t osdev;
                 ^~~~~
base/hwloc_base_util.c: In function ‘opal_hwloc_base_get_locality_string’:
base/hwloc_base_util.c:2207:30: error: ‘obj’ undeclared (first use in this function)
                     if (3 == obj->attr->cache.depth) {
                              ^~~
base/hwloc_base_util.c:2207:30: note: each undeclared identifier is reported only once for each function it appears in
```

It looks like ea80a20e108cb69efc67ad04ad968da7b85772af removed the declaration and initialization of `obj` for `HWLOC_API_VERSION < 0x20000`.

What do we want to do here?

FYI @bgoglin @hppritcha

**Comment by jsquyres** [comment]
@gpaulsen @hppritcha There was discussion on #7201 as to whether it should be back-ported to v4.0.x.  It doesn't look like it was, but just in case you guys have that one on deck for v4.0.x: be warned that breaking compatibility to hwloc <= v2.0 is a consequence.

**Comment by hppritcha** [comment]
@bgoglin i will take a look at patching this up.

**Comment by rhc54** [comment]
Wow - are you seriously holding us to work with something as ancient as hwloc v1.5?? I thought we only went back to 1.11, or maybe 1.10 (doubtful)

**Comment by bgoglin** [comment]
I thought you would have a CI testing over hwloc < 2.0.
Go ahead and bring back the obj definition, and add some #if HWLOC_API_VERSION to shutup the warning. I can look at it later today.
@rhc54 Don't worry, hwloc 1.11 likely breaks the same :)

**Comment by jsquyres** [comment]
> Wow - are you seriously holding us to work with something as ancient as hwloc v1.5?? I thought we only went back to 1.11, or maybe 1.10 (doubtful)

FWIW: this is what's currently in the code base:

https://github.com/open-mpi/ompi/blob/827e9f66af94b9269b15c3fd54b7e578f5740821/opal/mca/hwloc/external/configure.m4#L137-L147

So I have an MTT testing with 1.5.1.

I know that this is a side issue, but: I don't know if I have an opinion on what the oldest version is that we need to support.  What do popular distros ship with?  If we're considering bumping up the minimum hwloc supported version, we should probably look at what RHEL 7/CentOS 7 ships...?

**Comment by jsquyres** [comment]
> I thought you would have a CI testing over hwloc < 2.0.

Only in the nightly MTT builds -- not in CI, sorry.  ☹️ 

> Go ahead and bring back the obj definition, and add some #if HWLOC_API_VERSION to shutup the warning. I can look at it later today.

I probably will not have the cycles to do this any time soon.  ☹️  Beers for @bgoglin in Portland!

**Comment by rhc54** [comment]
Centos 7 is at hwloc v1.11 - don't know about other distros

**Comment by jsquyres** [comment]
> Centos 7 is at hwloc v1.11 - don't know about other distros

Good data point.  I'll add this to the [f2f agenda](https://github.com/open-mpi/ompi/wiki/Meeting-2020-02) (since Brice will be there, too).  That's orthogonal to this issue (that the code breaks for *any* version <2.0.x), but it's good to have that conversation.
