### ISSUE TITLE
common_ofi fails to compile with Libfabric v1.5

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7753]
When building Open MPI master with Libfabric v1.5, I get the following compile error:

```
make[2]: Entering directory `/home/jsquyres/git/ompi/opal/mca/common/ofi'
  CC       common_ofi.lo
common_ofi.c:197:51: warning: ‘struct fi_pci_attr’ declared inside parameter list will not be visible outside of this definition or declaration
 compare_cpusets(hwloc_topology_t topology, struct fi_pci_attr pci)
                                                   ^~~~~~~~~~~
common_ofi.c:197:63: error: parameter 2 (‘pci’) has incomplete type
 compare_cpusets(hwloc_topology_t topology, struct fi_pci_attr pci)
                                            ~~~~~~~~~~~~~~~~~~~^~~
common_ofi.c:197:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 compare_cpusets(hwloc_topology_t topology, struct fi_pci_attr pci)
 ^~~~~~~~~~~~~~~
common_ofi.c: In function ‘opal_mca_common_ofi_select_provider’:
common_ofi.c:303:24: error: storage size of ‘pci’ isn’t known
     struct fi_pci_attr pci;
                        ^~~
common_ofi.c:330:41: error: ‘struct fi_info’ has no member named ‘nic’
             if (NULL != current_provider->nic) {
                                         ^~
common_ofi.c:331:39: error: ‘struct fi_info’ has no member named ‘nic’
                 pci = current_provider->nic->bus_attr->attr.pci;
                                       ^~
common_ofi.c:359:5: warning: "OPAL_DEBUG_ENABLE" is not defined, evaluates to 0 [-Wundef]
 #if OPAL_DEBUG_ENABLE
     ^~~~~~~~~~~~~~~~~
common_ofi.c:369:1: warning: label ‘err_free_table’ defined but not used [-Wunused-label]
 err_free_table:
 ^~~~~~~~~~~~~~
common_ofi.c:303:24: warning: unused variable ‘pci’ [-Wunused-variable]
     struct fi_pci_attr pci;
                        ^~~
make[2]: *** [common_ofi.lo] Error 1
```

Either this needs to be protected with `#if`s, or we need to set a lower bound on what versions of Libfabric Open MPI will support (and fail during configure if Libfabric is too old).

Personally, I would prefer to keep supporting older Libfabric releases unless there's a reason not to.

It looks like the offending code was added by commit 167d75b42ac3ca4770d59c796c011d72e0fffde3 by @dancejic via #7641.  @dancejic is not assignable here on Github, so I'm assigning to @wckzhang and @bwbarrett because they're guilty by association.  😄

**Comment by dancejic** [comment]
I'll take a look and get a fix in as soon as possible. I think if libfabric 1.5 doesn't support the pci attributes there's no reason to even try and find the locality, so I'll discuss with the team on the best way of putting the `#if`s

**Comment by jsquyres** [comment]
@dancejic Thank you!

**Comment by rajachan** [comment]
https://github.com/open-mpi/ompi/commit/21bc9042e1ff9c3075ababda9eaf49ccc90f64db bumped the API requirement to 1.5 when adding the local/remote comm capabilities. Rather than adding `#if`s, the cleanest way to handle this would be to bump the requirement since the MTL depends on fi_nic now.

**Comment by jsquyres** [comment]
Do not forget: the OFI MTL is not the only user of Libfabric.

**Comment by dancejic** [comment]
sorry for the delays, I had some issues figuring out the configure code

https://github.com/open-mpi/ompi/pull/7771

**Comment by hppritcha** [comment]
Did #7771 fix this issue?

**Comment by gpaulsen** [comment]
Closing assuming fixed.

**Comment by jsquyres** [comment]
I confirm that this is not a problem on master HEAD today; I'm assuming it was fixed a long time ago.
