### ISSUE TITLE
openib fails to build with OFED 2.2.125 related to HAVE_DECL_IBV_EXP_QUERY_DEVICE

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#1208]
When building on an x86_64 RHEL 6.5 with OFED 2.2.125, I get a build error in openib.
> uname -a
Linux mpi01 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
> /sbin/lspci | grep -i mellanox
11:00.0 Network controller: Mellanox Technologies MT27500 Family [ConnectX-3]
90:00.0 InfiniBand: Mellanox Technologies MT25204 [InfiniHost III Lx HCA] (rev 20)

I get this error:
  CC       btl_openib_component.lo
../../../../../../git/ompi/opal/mca/btl/openib/btl_openib_component.c: In function ?init_one_port?:
../../../../../../git/ompi/opal/mca/btl/openib/btl_openib_component.c:829: error: ?struct ibv_exp_device_attr? has 
no member named ?ext_atom?
gmake[3]: *** [btl_openib_component.lo] Error 1

Last touched by @hjelmn in commit: 191aebb9c849a79dab304b012c7f6fb3ebab2bd1

@hjelmn - I don't see this on OFED 3.0.0.  I know OFED 2.2.x is quite old.  We may not want to support this old of an OFED version, but I though this was working a month ago (master).

**Comment by jsquyres** [comment]
I think you meant @hjelmn :)

**Comment by gpaulsen** [comment]
OFED 2.2 is too old, closing.
