### PR TITLE
v4.0.0: Fix configury for internal PMIx

### LINKED ISSUE #5871: 4.0rc4 won't compile with external PMIx 2.1.2
I'm having hard time getting v4 to work on our SLURM cluster. I configure it with external PMIx / HWLOC / libevent libraries:

```
./configure --prefix=[...] --enable-mpi-cxx --with-pmi --with-pmix=external --with-hwloc=external --with-libevent=external --with-mxm=${HPCX_MXM_DIR} --with-hcoll=${HPCX_HCOLL_DIR} --with-ucx=${HPCX_UCX_DIR} --with-knem=${KNEM_DIR} --with-platform=contrib/platform/mellanox/optimized
```
configure works ok
```
Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: external
PMIx support: 2x
```
but compilation fails
```
make[2]: Entering directory `/tmp/marcink/openmpi-4.0.0rc4/opal/mca/pmix/ext2x'
  CC       mca_pmix_ext2x_la-ext2x_local.lo
  CC       mca_pmix_ext2x_la-ext2x.lo
  CC       mca_pmix_ext2x_la-ext2x_client.lo
  CC       mca_pmix_ext2x_la-ext2x_component.lo
  CC       mca_pmix_ext2x_la-ext2x_server_north.lo
  CC       mca_pmix_ext2x_la-ext2x_server_south.lo
ext2x_local.c:21:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x_local.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
ext2x_component.c:26:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x_component.lo] Error 1
ext2x.c:42:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
ext2x_client.c:37:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x.lo] Error 1
ext2x_server_south.c:43:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x_client.lo] Error 1
ext2x_server_north.c:39:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
```
On the other hand, if I try to use the internal PMIx, then it configures and compiles fine
```
Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: external
PMIx support: internal
```
but `mpirun` fails to start anything due to a PMIx problem:
```
mpirun hostname
[c11-5.cluster:53592] [[42157,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 321
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_pmix_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
```

I guess those are two different problems. We need to compile with the SLURM plugin, hence we need the external PMIx (and hwloc + libevent) more. But the second problem seems more fundamental. `mpirun` fails even when run not from within a SLURM allocation.

Any ideas?

Marcin

### PR DESCRIPTION
**Pull request by rhc54**
Cherry-pick several fixes for when users configure ```--with-hwloc=internal``` or ```--with-hwloc=external```

Fixes #5871

### CODE REVIEW

**Comment by rhc54** [comment]
bot:ompi:test

**Comment by rhc54** [comment]
bot:ompi:retest

**Comment by gpaulsen** [comment]
I wasn't clear if you're still iterating on this PR, so I added the WIP-DNM label.  Please feel free to remove it when it's ready.

**Comment by gpaulsen** [comment]
In this comment: https://github.com/open-mpi/ompi/pull/5883#issuecomment-428433041
it sounds like @ggouaillardet is recommenting a cherry-pick of one of those commits to v4.0.x. (possibly in this PR, or possibly in another).  @rhc54 thoughts?

**Comment by rhc54** [comment]
We don't need to do that cherry-pick as this PR already contains that change. PR has been tested and verified by original reporter in #5871
