### ISSUE TITLE
attach fifo deleted on exit and not recreated on reattach

### ISSUE THREAD

**Issue by lee218llnl** [open-mpi/ompi#5115]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v 2.1.3, 3.0.1, and git master at commit 0552d127714b4b2b101236eebcf6e551238f68cd

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from source

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: x86
* Network type: psm2

-----------------------------

## Details of the problem

@rhc54 and @dongahn, I thought we had all the debugging kinks worked out, but in testing I notice that I have trouble when launching a job, attaching a debugger, detaching a debugger, and then reattaching the debugger. From what I can see, orterun deletes the debugger_attach_fifo when the debugger daemon exits, but then does not recreate it upon reattach.

Here's how you can reproduce

```
git clone https://github.com/llnl/launchmon.git
cd launchmon/
# modify test/src/be_kicker to set the "kill_detach_shutdown_time = 6"
CFLAGS="-g -O0" CXXFLAGS="-g -O0" ./configure --prefix=/nfs/tmp2/lee218/prefix/launchmon-1.0.3b --with-test-rm=orte --with-test-rm-launcher=mpirun --with-test-installed --with-test-nnodes=1 && make clean && make -j 8 install && make -j 8 check
cd test/src
# modify test.attach_4_detach to re-run fe_attach_smoketest $PID `pwd`/be_kicker $SIGNUM 1
./test.attach_4_detach
```

The additional fe_attach_smoketest will hang.

**Comment by rhc54** [comment]
Related to #5501

**Comment by gpaulsen** [comment]
We should retest this with new MPIR fixes that went in lately.

@lee218llnl Could you please retest this with latest master and bundled pmix.

**Comment by lee218llnl** [comment]
I was able to attach STAT to an OpenMPI job based on the master branch. I get this warning after attaching, which I imagine is expected:

Open MPI has detected that you have attached a debugger to this MPI
job, and that debugger is using the legacy "MPIR" method of
attachment.

Please note that Open MPI has deprecated the "MPIR" debugger
attachment method in favor of the new "PMIx" debugger attchment
mechanisms.

*** This means that future versions of Open MPI may not support the
*** "MPIR" debugger attachment method at all.  Specifically: the
*** debugger you just attached may not work with future versions of
*** Open MPI.

You may wish to contact your debugger vendor to inquire about support
for PMIx-based debugger attachment mechanisms. Meantime, you can
disable this warning by setting the OMPI_MPIR_DO_NOT_WARN envar to 1.
--------------------------------------------------------------------------

**Comment by lee218llnl** [comment]
I may have spoke too soon. The initial attach succeeds, but a subsequent one fails (this is an error message from LaunchMON/STAT):

<Jul 15 09:33:18> <Launchmon> (INFO): Open a FIFO (/var/tmp/lee218/ompi.rzwiz7.52649/pid.98754/0/debugger_attach_fifo) failed, errno(2)

Prior to attaching and during my active debug session, I can see the debugger_attach_fifo:

bash-4.2$ ll /var/tmp/lee218/ompi.rzwiz7.52649/pid.99183/0/
total 0
drwx------ 2 lee218 lee218 40 Jul 15 09:35 0
prw------- 1 lee218 lee218  0 Jul 15 09:35 debugger_attach_fifo

However, once I detach the debugger, the directory disappears:

bash-4.2$ ll /var/tmp/lee218/ompi.rzwiz7.52649/pid.99183/0/
ls: cannot access /var/tmp/lee218/ompi.rzwiz7.52649/pid.99183/0/: No such file or directory

**Comment by jsquyres** [comment]
Per discussion on 2019-07-16 Webex, @hppritcha says he will try to reproduce on master.

@lee218llnl Can you provide a little more information?

* Does this behavior work on v3.0.x?
* Does this behavior work on v3.1.x?
* Does this behavior work on v4.0.x?
* Does this behavior work on Spectrum MPI?

**Comment by lee218llnl** [comment]
It looks like 3.0.4, 3.1.4, and 4.0.1 all fail on the reattach case. Spectrum MPI succeeds on reattach.

**Comment by hppritcha** [comment]
@lee218llnl I don't see stat on rzansel.

**Comment by hppritcha** [comment]
Okay after some amount of hacking of launchmon with Open MPI 4.0.x I''m seeing this kind of output from the test:
```
LMON APP] singal handler installed for signum=10
<Nov 25 12:54:40> APP (INFO): stall for 3 secs
<Nov 25 12:54:43> APP (INFO): stall for 3 secs
[rzansel21:12742] 1 more process has sent help message help-mpi-btl-openib.txt / error in device init
[rzansel21:12742] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
<Nov 25 12:54:46> APP (INFO): stall for 3 secs
<Nov 25 12:54:49> APP (INFO): stall for 3 secs
<Nov 25 12:54:52> APP (INFO): stall for 3 secs
<Nov 25 12:54:55> APP (INFO): stall for 3 secs
<Nov 25 12:54:58> APP (INFO): stall for 3 secs
<Nov 25 12:54:59> SDBG_TRACER_ERROR (ERROR): [filename: sdbg_linux_ptracer.hxx, linenum: 95] [linux_ptracer_t::tracer_read] error returned from ptrace Input/output error
<Nov 25 12:54:59> SDBG_TRACER_ERROR (ERROR): BACKTRACE: 
launchmon: linux_tracer_exception_t::linux_tracer_exception_t(std::string const&, tracer_error_e)
launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::tracer_read(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, unsigned long, void*, int, bool)
launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::enable_breakpoint(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, breakpoint_base_t<unsigned long, unsigned int>&, bool, bool)
launchmon: linux_launchmon_t::handle_trap_after_attach_event(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&)
launchmon: launchmon_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::invoke_handler(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, launchmon_event_e, int)
launchmon: event_manager_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::poll_processes(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, launchmon_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&)
launchmon: event_manager_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::multiplex_events(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, launchmon_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&)
launchmon: driver_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::drive_engine(opts_args_t*)
launchmon: driver_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::drive(int, char**)
launchmon: linux_driver_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs>::driver_main(int, char**)
launchmon: main
libc.so.6: 0x25200
libc.so.6: __libc_start_main

<Nov 25 12:54:59> <LMON FE API> (ERROR): read_lmonp_msg returned a negative return code
<Nov 25 12:54:59> <LMON FE API> (ERROR): front end's connection to launchmon engine is disconnected?
<Nov 25 12:55:01> APP (INFO): stall for 3 secs
<Nov 25 12:55:04> APP (INFO): stall for 3 secs
<Nov 25 12:55:07> APP (INFO): stall for 3 secs
<Nov 25 12:55:10> APP (INFO): stall for 3 secs
<Nov 25 12:55:13> APP (INFO): stall for 3 secs
<Nov 25 12:55:16> APP (INFO): stall for 3 secs
<Nov 25 12:55:19> APP (INFO): stall for 3 secs
<Nov 25 12:55:22> APP (INFO): stall for 3 secs
<Nov 25 12:55:25> APP (INFO): stall for 3 secs
<Nov 25 12:55:28> APP (INFO): stall for 3 secs
<Nov 25 12:55:31> APP (INFO): stall for 3 secs
<Nov 25 12:55:34> APP (INFO): stall for 3 secs
<Nov 25 12:55:37> APP (INFO): stall for 3 secs
<Nov 25 12:55:40> APP (INFO): stall for 3 secs
<Nov 25 12:55:43> APP (INFO): stall for 3 secs
```

and from specturm  seeing pretty much the same behavior:
```
[hpp@rzansel40:src]$ .//test.attach_4_detach
[LMON APP] singal handler installed for signum=10
<Nov 25 13:02:01> APP (INFO): stall for 3 secs
<Nov 25 13:02:04> APP (INFO): stall for 3 secs
<Nov 25 13:02:07> APP (INFO): stall for 3 secs
<Nov 25 13:02:10> APP (INFO): stall for 3 secs
<Nov 25 13:02:13> APP (INFO): stall for 3 secs
<Nov 25 13:02:16> APP (INFO): stall for 3 secs
<Nov 25 13:02:19> APP (INFO): stall for 3 secs
<Nov 25 13:02:20> SDBG_TRACER_ERROR (ERROR): [filename: sdbg_linux_ptracer.hxx, linenum: 95] [linux_ptracer_t::tracer_read] error returned from ptrace Input/output error
<Nov 25 13:02:20> SDBG_TRACER_ERROR (ERROR): BACKTRACE: 
launchmon: linux_tracer_exception_t::linux_tracer_exception_t(std::string const&, tracer_error_e)
launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::tracer_read(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, unsigned long, void*, int, bool)
launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::enable_breakpoint(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, breakpoint_base_t<unsigned long, unsigned int>&, bool, bool)
launchmon: linux_launchmon_t::handle_trap_after_attach_event(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&)
launchmon: launchmon_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::invoke_handler(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, launchmon_event_e, int)
launchmon: event_manager_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::poll_processes(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, launchmon_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&)
launchmon: event_manager_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::multiplex_events(process_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&, launchmon_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>&)
launchmon: driver_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::drive_engine(opts_args_t*)
launchmon: driver_base_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs, my_thrinfo_t, elf_wrapper>::drive(int, char**)
launchmon: linux_driver_t<unsigned long, unsigned long, unsigned int, pt_regs, pt_regs>::driver_main(int, char**)
launchmon: main
libc.so.6: 0x25200
libc.so.6: __libc_start_main

<Nov 25 13:02:20> <LMON FE API> (ERROR): read_lmonp_msg returned a negative return code
<Nov 25 13:02:20> <LMON FE API> (ERROR): front end's connection to launchmon engine is disconnected?
<Nov 25 13:02:22> APP (INFO): stall for 3 secs
<Nov 25 13:02:25> APP (INFO): stall for 3 secs
<Nov 25 13:02:28> APP (INFO): stall for 3 secs
```

We had to hack the test script to specify RM_type=RM_orte, etc.

**Comment by lee218llnl** [comment]
I'm going to defer launchmon questions to @dongahn

**Comment by hppritcha** [comment]
well the rzansel admins pointed me to stat-cl.  Looks like somethings not working though.
With spectrum-mpi I get this behavior attaching to a hello world modified to hang in an mpi_barrier:
```
[hpp@rzansel23:~]$ stat-cl 93010
STAT started at 2019-11-26-10:15:19
Attaching to job launcher (null):93010 and launching tool daemons...
<Nov 26 10:15:19> <LMON FE API> (INFO): GCRYPT shared_key: 1981984690
<Nov 26 10:15:19> <LMON FE API> (INFO): GCRYPT setkey, 31383931:36343839:3039:0
<Nov 26 10:15:19> <Driver> (INFO): Unknown resource manager type: it could be misconfiguration in a rm config file.
<Nov 26 10:15:19> <LMON FE API> (ERROR): read_lmonp_msg returned a negative return code
<Nov 26 10:15:19> <LMON FE API> (ERROR): front end's connection to launchmon engine is disconnected?

```

I get the same behavior with Open MPI 4.0.2.

**Comment by lee218llnl** [comment]
what command did you use to launch your job? I think the currently install STAT assumes it's jsrun, since that is what most of our users do. I get similar errors when trying to attach to a job launched with mpirun.

**Comment by hppritcha** [comment]
well I trie to get back to this but it looks like somethings messed up with launchmon now:
```
(master *)./configure --prefix=$PWD/install_test CFLAGS="-g -O0" CXXFLAGS="-g -O0" --with-test-rm=orte --with-test-rm-launcher=mpirun --with-test-installed --with-test-nnodes=1 && make clean && make -j 8 install && make -j 8 check
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
```
@lee218llnl

**Comment by lee218llnl** [comment]
Can you try rerunning `bootstrap` and see if that fixes it?

**Comment by hppritcha** [comment]
hmm.  looks like I'm stuck with this till the sysadmins install libgcrypt-devel rpm.

**Comment by lee218llnl** [comment]
you could install libgcrpyt at the user level using Spack, or you could try installing it directly from source.

**Comment by hppritcha** [comment]
once again back to working on this.  I don't suppose launchmom requires a boost installation?

**Comment by lee218llnl** [comment]
@hppritcha I don't think LaunchMON requires boost, but STAT depends on MRNet and DynInst which do require boost. Is there a particular reason why you are asking?

**Comment by hppritcha** [comment]
```
 CXX      libmonbeapi_la-lmon_be_sync_mpi_generic.lo
  CXX      libmonbeapi_la-lmon_be_sync_mpi_bg.lo
  CXX      libmonbeapi_la-lmon_be_sync_mpi_bgq.lo
  CXX      libmonfeapi_la-lmon_fe.lo
  CXX      libmonfeapi_la-lmon_lmonp_msg.lo
  CXX      libmonfeapi_la-lmon_coloc_spawner.lo
  CXX      libmonfeapi_la-lmon_say_msg.lo
  CXX      libmonfeapi_la-sdbg_rm_map.lo
../../../../launchmon/src/sdbg_rm_map.cxx:58:31: fatal error: boost/tokenizer.hpp: No such file or directory
 #include <boost/tokenizer.hpp>
                               ^
compilation terminated.
  CXX      libmonfeapi_la-sdbg_self_trace.lo
  CXX      libmonfeapi_la-sdbg_opt.lo
  CXX      libmonfeapi_la-sdbg_rsh_spawner.lo
make[4]: *** [libmonfeapi_la-sdbg_rm_map.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/projects/hpctools/hpp/launchmon/launchmon/src/linux/lmon_api'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/projects/hpctools/hpp/launchmon/launchmon/src/linux'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/projects/hpctools/hpp/launchmon/launchmon/src'
```

**Comment by hppritcha** [comment]
note for myself:
```
 ./configure --prefix=$PWD/install_test CFLAGS="-g -O0" CXXFLAGS="-g -O0 -I /projects/opt/centos7/boost/1.59.0_gcc-6.2.0/include" --with-test-rm=orte --with-test-rm-launcher=mpirun --with-test-installed --with-test-nnodes=1 && make clean && make -j 8 install && make -j 8 check
```

**Comment by hppritcha** [comment]
@lee218llnl  did you check if the test fails with the OMPI 2.0.x releases?

**Comment by hppritcha** [comment]
I double checked and the reatttach works with both v2.0.x and v2.x branches. 

 Output from v2.x:
```
BOUT TO DO THE ATTACH SMOKE TEST
[cn61:17132] [[46056,0],0] Attaching debugger /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker
<Mar 17 15:48:11> <Launchmon> (INFO): Just continued the RM process out of the first trap
[cn61:17132] [[46056,0],0] orted_cmd: received add_local_procs
<Mar 17 15:48:11> APP (INFO): stall for 3 secs
[LMON APP] * Received SIGUSR1  * 
The hang unlocked
[LMON BE] signum: 10, argv[1]: 10 argc(3)
[LMON BE] subtest: 1, argv[2]: 1
[LMON BE(0)] Target process:    17140, MPI RANK:     0
[LMON BE(0)] Target process:    17141, MPI RANK:     1
[LMON FE] Please check the correctness of the following proctable
[LMON FE] host_name: cn61
[LMON FE] executable_name: /usr/projects/hpctools/hpp/launchmon/test/src/./hang_on_SIGUSR1
[LMON FE] pid: 17140(rank 0)
[LMON FE] 
[LMON FE] host_name: cn61
[LMON FE] executable_name: /usr/projects/hpctools/hpp/launchmon/test/src/./hang_on_SIGUSR1
[LMON FE] pid: 17141(rank 1)
[LMON FE] 

[LMON FE] RM type is 9

[LMON FE] RM launcher's pid is 17132
  PID TTY      STAT   TIME COMMAND
 2403 pts/0    Ss     0:00 /bin/bash -l
17125 pts/0    S+     0:00 /bin/sh ./test_script
17132 pts/0    Sl+    0:00 mpirun --debug-daemons -np 2 ./hang_on_SIGUSR1
17140 pts/0    Sl     0:00 ./hang_on_SIGUSR1
17141 pts/0    Sl     0:00 ./hang_on_SIGUSR1
17231 pts/0    S+     0:00 ./fe_attach_smoketest 17132 /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker 10 1
17232 pts/0    Z+     0:00 [launchmon] <defunct>
17234 pts/0    S      0:00 /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker 10 1 --lmonsharedsec=1874614445 --lmonsecchk=1875303802
17235 pts/0    R+     0:00 ps x
[LMON FE] CHECK for LMON_fe_detach
[LMON FE] PASS Criteria: launcher process(es) must not be traced.
DONE WITH ATTACH SMOKE TEST
<Mar 17 15:48:14> APP (INFO): 57 secs remain
<Mar 17 15:48:17> APP (INFO): 54 secs remain
<Mar 17 15:48:18> <LMON BE API> (ERROR): read_lmonp return a neg value
<Mar 17 15:48:20> APP (INFO): 51 secs remain
<Mar 17 15:48:23> APP (INFO): 48 secs remain
<Mar 17 15:48:26> APP (INFO): 45 secs remain
<Mar 17 15:48:29> APP (INFO): 42 secs remain
ABOUT TO REATTACH SMOKE TEST
[cn61:17132] [[46056,0],0] Attaching debugger /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker
[cn61:17132] [[46056,0],0] orted_cmd: received add_local_procs
<Mar 17 15:48:31> <Launchmon> (INFO): Just continued the RM process out of the first trap
[LMON APP] * Received SIGUSR1  * 
<Mar 17 15:48:31> APP (INFO): 39 secs remain
[LMON BE] signum: 10, argv[1]: 10 argc(3)
[LMON BE] subtest: 1, argv[2]: 1
[LMON BE(0)] Target process:    17140, MPI RANK:     0
[LMON BE(0)] Target process:    17141, MPI RANK:     1
[LMON FE] Please check the correctness of the following proctable
[LMON FE] host_name: cn61
[LMON FE] executable_name: /usr/projects/hpctools/hpp/launchmon/test/src/./hang_on_SIGUSR1
[LMON FE] pid: 17140(rank 0)
[LMON FE] 
[LMON FE] host_name: cn61
[LMON FE] executable_name: /usr/projects/hpctools/hpp/launchmon/test/src/./hang_on_SIGUSR1
[LMON FE] pid: 17141(rank 1)
[LMON FE] 

[LMON FE] RM type is 9

[LMON FE] RM launcher's pid is 17132
  PID TTY      STAT   TIME COMMAND
 2403 pts/0    Ss     0:00 /bin/bash -l
17125 pts/0    S+     0:00 /bin/sh ./test_script
17132 pts/0    Sl+    0:00 mpirun --debug-daemons -np 2 ./hang_on_SIGUSR1
17140 pts/0    Sl     0:00 ./hang_on_SIGUSR1
17141 pts/0    Sl     0:00 ./hang_on_SIGUSR1
17256 pts/0    S+     0:00 ./fe_attach_smoketest 17132 /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker 10 1
17257 pts/0    Z+     0:00 [launchmon] <defunct>
17259 pts/0    S      0:00 /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker 10 1 --lmonsharedsec=1356577099 --lmonsecchk=1160180225
17260 pts/0    R+     0:00 ps x
[LMON FE] CHECK for LMON_fe_detach
[LMON FE] PASS Criteria: launcher process(es) must not be traced.
DONE WITH REATTACH SMOKE TEST
```

whereas here's what we see with v3.1.x
```
ABOUT TO DO THE ATTACH SMOKE TEST
[[44014,0],0] Attaching debugger /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker[[44014,0],0] Spawning debugger daemons /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker[cn61:23274] [[44014,0],0] orted_cmd: received add_local_procs
<Mar 17 15:54:13> <Launchmon> (INFO): Just continued the RM process out of the first trap
HEYI got rc = 0
[LMON APP] * Received SIGUSR1  * 
The hang unlocked
[LMON BE] signum: 10, argv[1]: 10 argc(3)
[LMON BE] subtest: 1, argv[2]: 1
[LMON BE(0)] Target process:    23280, MPI RANK:     0
[LMON BE(0)] Target process:    23281, MPI RANK:     1
[LMON FE] Please check the correctness of the following proctable
[LMON FE] host_name: cn61
[LMON FE] executable_name: /usr/projects/hpctools/hpp/launchmon/test/src/./hang_on_SIGUSR1
[LMON FE] pid: 23280(rank 0)
[LMON FE] 
[LMON FE] host_name: cn61
[LMON FE] executable_name: /usr/projects/hpctools/hpp/launchmon/test/src/./hang_on_SIGUSR1
[LMON FE] pid: 23281(rank 1)
[LMON FE] 

[LMON FE] RM type is 9

[LMON FE] RM launcher's pid is 23274
  PID TTY      STAT   TIME COMMAND
 2403 pts/0    Ss     0:00 /bin/bash -l
23267 pts/0    S+     0:00 /bin/sh ./test_script
23274 pts/0    Sl+    0:00 mpirun --debug-daemons -np 2 ./hang_on_SIGUSR1
23280 pts/0    Sl     0:00 ./hang_on_SIGUSR1
23281 pts/0    Sl     0:00 ./hang_on_SIGUSR1
23371 pts/0    S+     0:00 ./fe_attach_smoketest 23274 /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker 10 1
23372 pts/0    Z+     0:00 [launchmon] <defunct>
23374 pts/0    S      0:00 /usr/projects/hpctools/hpp/launchmon/test/src/be_kicker 10 1 --lmonsharedsec=1949156400 --lmonsecchk=234188557
23375 pts/0    R+     0:00 ps x
[LMON FE] CHECK for LMON_fe_detach
[LMON FE] PASS Criteria: launcher process(es) must not be traced.
DONE WITH ATTACH SMOKE TEST
<Mar 17 15:54:16> APP (INFO): 57 secs remain
<Mar 17 15:54:19> APP (INFO): 54 secs remain
<Mar 17 15:54:20> <LMON BE API> (ERROR): read_lmonp return a neg value
<Mar 17 15:54:22> APP (INFO): 51 secs remain
<Mar 17 15:54:25> APP (INFO): 48 secs remain
<Mar 17 15:54:28> APP (INFO): 45 secs remain
<Mar 17 15:54:31> APP (INFO): 42 secs remain
ABOUT TO REATTACH SMOKE TEST
<Mar 17 15:54:33> <Launchmon> (INFO): Open a FIFO (/usr/projects/hpctools/hpp/launchmon/test/src/tmpdir/ompi.cn61.1547/pid.23274/0/debugger_attach_fifo) failed, errno(2)
<Mar 17 15:54:33> <Launchmon> (INFO): Just continued the RM process out of the first trap
<Mar 17 15:54:34> APP (INFO): 39 secs remain
```

**Comment by lee218llnl** [comment]
@hppritcha do you need any more info from me regarding this issue or do you have everything you need to debug/fix?

**Comment by hppritcha** [comment]
@lee218llnl don't think I need more from you at the moment for this bug.  I'm adding stuff here so as not to forget.

**Comment by dongahn** [comment]
I think errno=2 is `ENOENT` which probably means that the FIFO file doesn't exist. ORTE doesn't create a FIFO for reattach?

**Comment by lee218llnl** [comment]
This was a previous post of mine on this issue, which confirms Dong's suspicion:

> I may have spoke too soon. The initial attach succeeds, but a subsequent one fails (this is an error message from LaunchMON/STAT):
> 
> <Jul 15 09:33:18> (INFO): Open a FIFO (/var/tmp/lee218/ompi.rzwiz7.52649/pid.98754/0/debugger_attach_fifo) failed, errno(2)
> 
> Prior to attaching and during my active debug session, I can see the debugger_attach_fifo:
> 
> bash-4.2$ ll /var/tmp/lee218/ompi.rzwiz7.52649/pid.99183/0/
> total 0
> drwx------ 2 lee218 lee218 40 Jul 15 09:35 0
> prw------- 1 lee218 lee218 0 Jul 15 09:35 debugger_attach_fifo
> 
> However, once I detach the debugger, the directory disappears:
> 
> bash-4.2$ ll /var/tmp/lee218/ompi.rzwiz7.52649/pid.99183/0/
> ls: cannot access /var/tmp/lee218/ompi.rzwiz7.52649/pid.99183/0/: No such file or directory

**Comment by hppritcha** [comment]
@lee218llnl 

I'm more curious about what's going on that generates this message
```
<Mar 18 16:57:33> <LMON BE API> (ERROR): read_lmonp return a neg value
```
it seems to be at that point that the mpirun process sees some child process exit unexpectedly and assumes its needing to clean up.  Does a process exit after generating this error message? Note the error reading the fifo comes much later during the second attach attempt.

**Comment by lee218llnl** [comment]
@hppritcha no MPI processes are exiting, they should all be in a hang state (one task in an infinite loop, one task on an MPI_WaitAll, and the rest in and MPI_Barrier).

**Comment by hppritcha** [comment]
@lee218llnl  I'm more interested in the Launcmon processes.  How does the BE launchmon process get started?  mpirun is acting like some process it started (not the MPI ranks though) exited unexpectedly just after this error message from LMON BE API appears.  That's when the fifo clean occurs.

**Comment by dongahn** [comment]
@hppritcha: The launchmon backend processes (tool daemons) should be started by orterun or OMPI's process management layer more generally speaking. For this system, the launchmon engine that interfaces with orterun will write the path and arguments of the backend (BE) processes into the address space of orterun process and poke it by sending a byte to the FIFO "I wrote all the info; please launch my daemons".  If FIFO isn't working, mpirun won't be able to do this for us. 

The protocol is documented in MPIR spec: https://www.mpi-forum.org/docs/mpir-specification-10-11-2010.pdf

Hopefully this helps.

**Comment by dongahn** [comment]
> I'm more curious about what's going on that generates this message

> <Mar 18 16:57:33> <LMON BE API> (ERROR): read_lmonp return a neg value
it seems to be at that point that the mpirun process sees some child process exit unexpectedly and assumes its needing to clean up. Does a process exit after generating this error message? Note the error reading the fifo comes much later during the second attach attempt.

@hppritcha: I don't understand how and why this error message is being printed. This error happens when a backend daemon had an error in reading a message from another launchmon component like the luncheon engine.

**Comment by dongahn** [comment]
Looking further the posting, it looks to me like you can ignore this error message for now and look at why the orterun doesn't create FIFO for reattach? From your earlier testing, reattach worked for both v2.0.x and v2.x branches even with the same error message?

Sorry I can't be any better help..

**Comment by hppritcha** [comment]
won't fix in 3.0 and 3.1 release streams as these are end of life.

**Comment by hppritcha** [comment]
note for master, the fix for this problem will lie in other projects, prrte/pmix/mpir-shim

**Comment by hppritcha** [comment]
closed via #7609

**Comment by lee218llnl** [comment]
While it looks like the session directory still exists after detaching the initial debug session, I still have problems when trying to reattach to the same job (i.e., launchmon hangs). @hppritcha did you retry your reattach launchmon test on the commit for #7609? @dongahn we may need your eyes on this one to see what is going on inside launchmon and what state it see's orterun in.
