### ISSUE TITLE
[v4.1.x] ompi compilation error with CUDA enabled libfabric

### ISSUE THREAD

**Issue by wenduwan** [open-mpi/ompi#11381]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

[Testing on head of v4.1.x](https://github.com/open-mpi/ompi/commit/a9a9d417a725ba98ad618648dec990072ce9ed94)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
git clone --recursive https://github.com/open-mpi/ompi.git
cd ompi
git checkout v4.1.x  ## It works on v5.0.x
git submodule update --init --recursive
./autogen.pl
./configure --prefix=<install dir> --with-sge --without-verbs --with-libfabric=<cuda enabled libfabric > --enable-mca-no-build=btl-uct --disable-man-pages --with-libevent=external --with-hwloc=external --enable-cuda --with-cuda=/usr/local/cuda --with-cuda-libdir=/usr/local/cuda/lib64/stubs --disable-builtin-atomics
make -j
```

`make` error
```
mtl_ofi_component.c: In function 'ompi_mtl_ofi_component_close':
mtl_ofi_component.c:298:5: error: implicit declaration of function 'mca_common_cuda_fini'; did you mean 'ompi_comm_cid_init'? [-Werror=implicit-function-declaration]
     mca_common_cuda_fini();
     ^~~~~~~~~~~~~~~~~~~~
     ompi_comm_cid_init
cc1: some warnings being treated as errors
make[2]: *** [mtl_ofi_component.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/ec2-user/ompi-copy/ompi/mca/mtl/ofi'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ec2-user/ompi-copy/ompi'
make: *** [all-recursive] Error 1
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

No submodule on v4.1.x branch.

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: p4d.24xlarge instance with cuda toolkit 11.6 installed
* Network type: EFA

-----------------------------

## Details of the problem

See reproducing steps above.

**Comment by lrbison** [comment]
I left out the libfabric option to configure, but otherwise did the same configure line, and my v4.1.x build succeeded.

Can you confirm that the `./configure` command indicates CUDA support will be built?

If you remove the libfabric argument to configure does it work?

**Comment by wenduwan** [comment]
Thanks for your pointer. I tried without `--with-libfabric` and make works.

So based on this datapoint, it's likely a combination of ompi 4.1.x + ofi + cuda

**Comment by wenduwan** [comment]
Since the PR has been merged, shall we close this issue?

**Comment by jsquyres** [comment]
Can you confirm that the fix works for you in the 4.1.5rc that was just released yesterday?

https://www.open-mpi.org/software/ompi/v4.1/

**Comment by wenduwan** [comment]
Yes. https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.5rc4.tar.gz is verified. `make` works!

Thanks everyone!
