### ISSUE TITLE
4.0rc4 won't compile with external PMIx 2.1.2

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#5871]
I'm having hard time getting v4 to work on our SLURM cluster. I configure it with external PMIx / HWLOC / libevent libraries:

```
./configure --prefix=[...] --enable-mpi-cxx --with-pmi --with-pmix=external --with-hwloc=external --with-libevent=external --with-mxm=${HPCX_MXM_DIR} --with-hcoll=${HPCX_HCOLL_DIR} --with-ucx=${HPCX_UCX_DIR} --with-knem=${KNEM_DIR} --with-platform=contrib/platform/mellanox/optimized
```
configure works ok
```
Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: external
PMIx support: 2x
```
but compilation fails
```
make[2]: Entering directory `/tmp/marcink/openmpi-4.0.0rc4/opal/mca/pmix/ext2x'
  CC       mca_pmix_ext2x_la-ext2x_local.lo
  CC       mca_pmix_ext2x_la-ext2x.lo
  CC       mca_pmix_ext2x_la-ext2x_client.lo
  CC       mca_pmix_ext2x_la-ext2x_component.lo
  CC       mca_pmix_ext2x_la-ext2x_server_north.lo
  CC       mca_pmix_ext2x_la-ext2x_server_south.lo
ext2x_local.c:21:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x_local.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
ext2x_component.c:26:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x_component.lo] Error 1
ext2x.c:42:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
ext2x_client.c:37:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x.lo] Error 1
ext2x_server_south.c:43:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [mca_pmix_ext2x_la-ext2x_client.lo] Error 1
ext2x_server_north.c:39:10: fatal error: ext2x.h: No such file or directory
 #include "ext2x.h"
          ^~~~~~~~~
compilation terminated.
```
On the other hand, if I try to use the internal PMIx, then it configures and compiles fine
```
Miscellaneous
-----------------------
CUDA support: no
HWLOC support: external
Libevent support: external
PMIx support: internal
```
but `mpirun` fails to start anything due to a PMIx problem:
```
mpirun hostname
[c11-5.cluster:53592] [[42157,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 321
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_pmix_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
```

I guess those are two different problems. We need to compile with the SLURM plugin, hence we need the external PMIx (and hwloc + libevent) more. But the second problem seems more fundamental. `mpirun` fails even when run not from within a SLURM allocation.

Any ideas?

Marcin

**Comment by rhc54** [comment]
The second problem is indeed different. Basically, the internal PMIx build is silently failing, leaving you without any PMIx support. Can you please send us the ```opal/mca/pmix/pmix3x/pmix/config.log``` file from that configure?

The first problem looks like a different configure issue where OMPI isn't setting the ```CPPFLAGS``` to point to the PMIx installation. I'll take a peek at it.

**Comment by angainor** [comment]
I should also add that `master` version `OMPI_REPO_REV "date2018-10-09"` compiles and works fine with external PMIx (give or take issue #5872 I just submitted). 

`config.log` attached.

[config.log.gz](https://github.com/open-mpi/ompi/files/2460067/config.log.gz)

**Comment by rhc54** [comment]
Okay, at least that is a known problem we fixed recently on master - PR should resolve that one. I'll look at the other problem after breakfast 😄

**Comment by rhc54** [comment]
@angainor I checked the first issue and fixed a few minor typos, but I don't believe they should have impacted the build. Can you please try the PR and see if it fixes both observed issues?

**Comment by rhc54** [comment]
Sigh - never mind, old fossil brain misread your error report. I found the problem - a missing file in the tarball. Should be fixed by PR - can you please verify?

**Comment by angainor** [comment]
I'll only be able to do that in a few hours.

m

On Oct 9, 2018 15:44, "Ralph Castain" <notifications@github.com> wrote:

@angainor <https://github.com/angainor> I checked the first issue and fixed
a few minor typos, but I don't believe they should have impacted the build.
Can you please try the PR and see if it fixes both observed issues?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/open-mpi/ompi/issues/5871#issuecomment-428197385>, or mute
the thread

**Comment by angainor** [comment]
@rhc54 The patch didn't work: the PR modifies the `ext2x.h`, which indeed doesn't exist. So I copied one from `master` and then applied the patch, which worked. I then needed to re-run `aclocal/automake/autoconf` to get things working (your patches modified the configury..). Configure went fine, but when I compile I now see this:

```
make[2]: Entering directory `/tmp/marcink/openmpi-4.0.0rc4/opal/mca/crs'
  CCLD     libmca_crs.la
  GENERATE opal_crs.7
Option package-version requires an argument
Usage: ../../../config/make_manpage.pl --package-name=<package name> --package-version=<package version> --ompi-date=<ompi date> --opal-date=<opal date> --orte-date=<orte date> --input=<input file> --output=<output file> [--nocxx] [ --nofortran] [--nof08]
make[2]: *** [opal_crs.7] Error 1
```
So I guess my `autoconf` didn't work well enough. I did see this error:

```
sh: 1: config/opal_get_version.sh: not found
```
Can I fix this? Otherwise maybe you can provide a tar ball?

m

**Comment by rhc54** [comment]
Hmmm...that makes no sense. The patch doesn't modify ext2x.h, it adds it. Let me see if the path has a problem.

**Comment by rhc54** [comment]
Actually, I think we miss-communicated. My patch was meant to apply to a git clone of the v4.0.x branch, not to a tarball. It adds the ext2x.h file to the tarball, making a small mod to it. You would indeed have to then re-run autogen.

Probably the best thing is to wait until this gets committed and then check the nightly v4.0 tarball. I suspect it should be processed soon.

**Comment by angainor** [comment]
@rhc54 yea, I tried to apply the patch to the tar ball. I'll try again tomorrow.

**Comment by angainor** [comment]
@rhc54 @ggouaillardet I've downloaded the newest 4.0.x branch. It compiles and runs fine with my external PMIx, but it still doesn't compile with the internal one. From OpenMPI configure:

```
configure:5919: --- MCA component pmix:pmix3x (m4 configuration macro)
configure:164003: checking for MCA component pmix:pmix3x compile mode
configure:164009: result: dso
configure:164075: checking if PMIx timing is enabled
configure:164082: result: no (disabled)
configure:164095: checking if want to install standalone libpmix
configure:164101: result: no
configure:164167: OPAL configuring in opal/mca/pmix/pmix3x/pmix
configure:164248: running /bin/sh './configure' --with-devel-headers  --with-pmix-symbol-rename=OPAL_MCA_PMIX3X_ --enable-embedded-mode --disable-debug --disable-pmix-timing --without-tests-examples --disable-pmix-binaries --disable-pmix-backward-compatibility --disable-visibility --enable-embedded-libevent --with-libevent-header=\"opal/mca/event/external/external.h\"  '--prefix=/cluster/projects/nn9999k/marcink/software/openmpi/4.0.y' '--enable-mpi-cxx' '--enable-shared' '--with-pmi' '--with-pmix=internal' '--with-hwloc=external' '--with-libevent=external' '--with-mxm=/cluster/software/hpcx/2.2/mxm' '--with-hcoll=/cluster/software/hpcx/2.2/hcoll' '--with-ucx=/cluster/software/hpcx/2.2/ucx' '--with-knem=/opt/knem-1.1.3.90mlnx1/' 'CFLAGS=-DNDEBUG -O3 -g ' 'CPPFLAGS=-I/tmp/marcink/ompi-4.0.x -I/tmp/marcink/ompi-4.0.x -I/tmp/marcink/ompi-4.0.x/opal/include -I/tmp/marcink/ompi-4.0.x/opal/include    ' --cache-file=/dev/null --srcdir=. --disable-option-checking
configure:164258: /bin/sh './configure' *failed* for opal/mca/pmix/pmix3x/pmix
configure:164305: checking if v3.x component is to be used
configure:164312: result: yes - using the internal v3.x library
configure:164333: checking PMIx extra wrapper CPPFLAGS
configure:164335: result: 
configure:164337: checking PMIx extra wrapper LDFLAGS
configure:164339: result: 
configure:164341: checking PMIx extra wrapper LIBS
configure:164343: result: 
configure:164869: checking if MCA component pmix:pmix3x can compile
configure:164871: result: no
```

The PMIx `config.log` attached.

[config.log.gz](https://github.com/open-mpi/ompi/files/2463752/config.log.gz)

**Comment by rhc54** [comment]
Yex - it needs this patch in order to solve that problem. Did you apply this patch first?

**Comment by angainor** [comment]
@rhc54 OK, I did not understand that. Now I applied #5874 to today's 4.0.x branch, and both problems are gone. Thanks!

**Comment by gpaulsen** [comment]
@angainor, glad to hear things are working now.  #5874 has gone out in Open MPI v4.0.0rc5, available here: https://www.open-mpi.org/software/ompi/v4.0/

**Comment by angainor** [comment]
@gpaulsen Compiled rc5 with our external pmix 2.1.4 - works fine both with `mpirun`, and `srun`. Thanks!
