### ISSUE TITLE
Fortran ident string link error with --disable-weak-symbols

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#9698]
On master, on Linux, when configured with `--disable-weak-symbols`, we get a link error:

```
make[1]: Entering directory `/home/jsquyres/git/o2/ompi/mpi/fortran/mpif-h'
  CCLD     libmpi_mpifh.la
profile/.libs/libmpi_mpifh_pmpi.a(pinit_f.o):(.rodata+0x0): multiple definition of `ident'
.libs/init_f.o:(.rodata+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [libmpi_mpifh.la] Error 1
```

It looks like this error was introduced in b2ee56aa8148cdc04b352d11949af894688de90f -- @bwbarrett can you have a look?

**Comment by bwbarrett** [comment]
The error was actually introduced with Austen's recent ident warnings cleanup (9f15ca612df77e39398191f1cea1f5d797876c4c).  That said, I'll post a PR to fix shortly.

**Comment by bwbarrett** [comment]
Fix is merged to master.  9f15ca6 didn't get backported to any of the release branches, so closing the ticket.

**Comment by awlauria** [comment]
Thanks @bwbarrett 

I ported the change series back to v5 here: https://github.com/open-mpi/ompi/pull/9702
