### PR TITLE
opal/mca/threads/argobots: fix compilation error

### LINKED ISSUE #7697: Argobots: Missing _Atomic qualifier in threads_argobots_mutex.c
I tried building the Argobots integration with the current Clang trunk while testing #7675. Clang seems to be more strict about the `_Atomic` qualifier than GCC so the build fails: 

```
../../../../../opal/mca/threads/argobots/threads_argobots_mutex.c:107:13: error: address argument to atomic operation must be a pointer to _Atomic type ('intptr_t *' (aka 'long *') invalid)
        if (opal_atomic_compare_exchange_strong_ptr(
            ^
../../../../../opal/include/opal/sys/atomic_stdc.h:91:71: note: expanded from macro 'opal_atomic_compare_exchange_strong_ptr'
#define opal_atomic_compare_exchange_strong_ptr(addr, compare, value) atomic_compare_exchange_strong_explicit (addr, compare, value, memory_order_relaxed, memory_order_relaxed)
                                                                      ^                                        ~~~~
/home/h4/jschuch/opt/clang-trunk/lib/clang/11.0.0/include/stdatomic.h:127:49: note: expanded from macro 'atomic_compare_exchange_strong_explicit'
#define atomic_compare_exchange_strong_explicit __c11_atomic_compare_exchange_strong
                                                ^
../../../../../opal/mca/threads/argobots/threads_argobots_mutex.c:124:13: error: address argument to atomic operation must be a pointer to _Atomic type ('intptr_t *' (aka 'long *') invalid)
        if (opal_atomic_compare_exchange_strong_ptr((intptr_t *)cond,
            ^                                       ~~~~~~~~~~~~~~~~
../../../../../opal/include/opal/sys/atomic_stdc.h:91:71: note: expanded from macro 'opal_atomic_compare_exchange_strong_ptr'
#define opal_atomic_compare_exchange_strong_ptr(addr, compare, value) atomic_compare_exchange_strong_explicit (addr, compare, value, memory_order_relaxed, memory_order_relaxed)
                                                                      ^                                        ~~~~
/home/h4/jschuch/opt/clang-trunk/lib/clang/11.0.0/include/stdatomic.h:127:49: note: expanded from macro 'atomic_compare_exchange_strong_explicit'
#define atomic_compare_exchange_strong_explicit __c11_atomic_compare_exchange_strong
                                                ^
2 errors generated.
```

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
This patch fixes #7697 by properly using OPAL's atomic type.
I confirmed that it works with Clang 7, Clang 9, GCC 4.8.5, and ICC 17 on an Intel server.

Signed-off-by: Shintaro Iwasaki <siwasaki@anl.gov>

### CODE REVIEW

**Comment by jsquyres** [comment]
ok to test
