### ISSUE TITLE
configure help wrong for --with-libltdl, --with-hwloc

### ISSUE THREAD

**Issue by loveshack** [open-mpi/ompi#1092]
configure --help says that --with-libltdl=external and --with-hwloc=external can be specified to use external libraries, but "external" is actually interpreted as a directory name in both cases, and configuration fails.

**Comment by rhc54** [comment]
I'm not able to replicate that problem on the current 1.10.1 release candidate:

```
--- MCA component hwloc:external (m4 configuration macro, priority 90)
checking for MCA component hwloc:external compile mode... static
checking --with-hwloc-libdir value... simple ok (unspecified)
checking looking for external hwloc in... (default search paths)
checking hwloc.h usability... no
checking hwloc.h presence... no
checking for hwloc.h... no
checking if MCA component hwloc:external can compile... no
configure: WARNING: MCA component "external" failed to configure properly
configure: WARNING: This component was selected as the default
configure: error: Cannot continue
```

Looking at the configure log, it appears it did exactly what it was supposed to do:

```
configure:66802: checking for m4 configure components in framework hwloc
configure:66804: result: external, hwloc191
configure:66891: checking for MCA component hwloc:external compile mode
configure:66894: result: static
configure:66978: checking --with-hwloc-libdir value
configure:66981: result: simple ok (unspecified)
configure:67010: checking looking for external hwloc in
configure:67017: result: (default search paths)
configure:67079: checking hwloc.h usability
configure:67079: gcc -std=gnu99 -c -g -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing -pthread   conftest.c >&5
conftest.c:568:19: fatal error: hwloc.h: No such file or directory
 #include <hwloc.h>
                   ^
compilation terminated.
configure:67079: $? = 1
```

Can you confirm what version of OMPI you were using?

**Comment by loveshack** [comment]
rhc54 <notifications@github.com> writes:

> I'm not able to replicate that problem on the current 1.10.1 release candidate:

Strangely, I now can't either with hwloc -- apologies -- but I can with
ltdl:

```
$ ./configure --with-libltdl=external |& tail -n5
--- MCA component dl:libltdl (m4 configuration macro, priority 50)
checking for MCA component dl:libltdl compile mode... static
checking --with-libltdl value... not found
configure: WARNING: Directory external not found
configure: error: Cannot continue
```

[That did work with 1.6.5 -- I had to change it in the Debian packaging
for that version.]

The only relevant changes I can think of since when I saw the error for
hwloc are maybe re-autogen'ing and removing the installed openmpi.  I'm
pretty sure it was copy/paste too, so wasn't a typo.  Oh well...

> Can you confirm what version of OMPI you were using?

1.10.0 (on Debian stable).  Sorry, I certainly meant to say.  I looked
for relevant changes in the repo before reporting, and couldn't see any.

**Comment by opoplawski** [comment]
```
$ ./openmpi-1.10.5/configure --help
...
  --with-libltdl(=DIR)    Build libltdl support, optionally adding
                          DIR/include, DIR/lib, and DIR/lib64 to the search
                          path for headers and libraries
```
makes not reference of "external".  Very annoying that it is inconsistent, but...

**Comment by jsquyres** [comment]
@opoplawski I hear what you're saying.  Sorry!  Let me at least explain why it is the way it is...

hwloc has the "internal" vs. "external" designation because there's an embedded copy inside Open MPI (just to make sure we have the ability to have a modern enough version of hwloc, etc.).  Hence, you have three options:

1. Use the internal/embedded copy of hwloc
1. Use an external hwloc, specified by the `DIR` token in `--with-hwloc=DIR`
1. Use an external hwloc, found in default compiler/linker locations (i.e., `--with-hwloc=external`)

The `external` token option is necessary because without it, `--with-hwloc` would be ambiguous between the 1st and 3rd options.

Libtldl no longer has that distinction -- it became too problematic to embed (see all the issues and PRs linked from https://github.com/open-mpi/ompi/issues/311 for what happened here -- it was a long, complicated saga -- https://github.com/open-mpi/ompi/pull/410 was the final solution), so it can *only* be "external".  As such, it made sense to make `--with-libltdl` be just like every other `--with-FOO` option (i.e., that it does not recognize the `external` token).

FWIW, you likely don't need the libltdl library any more since we have a dlopen plugin natively in Open MPI that performs pretty much the same functionality as libltdl.  So if you want to drop `--with-libltdl` from your build (and the corresponding dependency on libltdl), you can probably do so.

**Comment by gpaulsen** [comment]
I think we can close this now. @loveshack @jsquyres do you agree?

**Comment by jsquyres** [comment]
Looks like all the fixed were merged.  Closing.
