### ISSUE TITLE
build failure -- main 28d0458  -- src/.libs/libompi-prrte.so: undefined reference to `PMIx_Group_operation_string'

### ISSUE THREAD

**Issue by ashterenli** [open-mpi/ompi#13532]
building main branch of ompi, commit https://github.com/open-mpi/ompi/commit/28d04584185410a48d5d6d78e8a95dba76785ad9

with intel 2025.1.0.666, on azure linux  6.6.96.2-2.azl3

I get:

```
/usr/bin/ld: ../../../src/.libs/libompi-prrte.so: undefined reference to `PMIx_Group_operation_string'
/usr/bin/ld: ../../../src/.libs/libompi-prrte.so: undefined reference to `pmix_show_help_add_data'
/usr/bin/ld: ../../../src/.libs/libompi-prrte.so: undefined reference to `PMIx_Info_list_add_value'
```

The full log is attached.

[ompi-main-bld.log](https://github.com/user-attachments/files/23744383/ompi-main-bld.log)

I built pmix 6.0.0, which is correctly picked up by ompi:

```
*** Configuring PMIx
checking for pmix pkg-config name... /data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/lib/pkgconfig/pmix.pc   checking if pmix pkg-config module exists... yes
checking for pmix pkg-config cflags... -I/data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/include -I/data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/include/pmix -I/data/ashterenli/spe-tst5/install/libevent-2.1.12-stable/include -I/data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/hwloc-2.12.2/include -I/usr/include/libxml2                  checking for pmix pkg-config ldflags... -Wl,-rpath -Wl,/data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/lib -Wl,--enable-new-dtags                                                                                                           checking for pmix pkg-config static ldflags... -Wl,-rpath -Wl,/data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/lib -Wl,--enable-new-dtags                                                                                                    checking for pmix pkg-config libs... -lpmix
checking for pmix pkg-config static libs... -lpmix
checking for pmix.h... yes
checking for PMIx_Init... yes
checking if pmix requires libnl v1 or v3... none
checking if external PMIx version is 4.2.0 or greater... yes
```
and
```
Required Packages
-----------------------
HWLOC: yes (pkg-config: /data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/hwloc-2.12.2)
Libevent: yes (/data/ashterenli/spe-tst5/install/libevent-2.1.12-stable)
PMIx: yes (pkg-config: /data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0)
```

and the symbols are defined in the pmix-6.0.0 lib that I built:

```
$ nm /data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/lib/libpmix.so | grep PMIx_Group_operation_string
00000000000f4e00 T PMIx_Group_operation_string

$ nm /data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/lib/libpmix.so | grep pmix_show_help_add_data
0000000000131430 T pmix_show_help_add_data

$ nm /data/ashterenli/spe-tst5/install/u_intel/2025.1.0.666/pmix-6.0.0/lib/libpmix.so | grep PMIx_Info_list_add_value
0000000000149a00 T PMIx_Info_list_add_value
```
so I'm not sure why the undefined reference error.

Perhaps I need to build pmix-6 with some extra flags, to work with ompi main?
I use only `--with-libevent=... --with-hwloc=...`.

Thank you

Anton

**Comment by ashterenli** [comment]
I can successfully build with `--with-pmix=internal`:
```
Open MPI: 6.1.0a1
PMIX: 6.0.0a1
```

**Comment by ggouaillardet** [comment]
FWIW I successfully built Open MPI `main` branch vs external PMIx `6.0.0` (installed from the tarball)
Per a recent comment on an unrelated issue (https://github.com/open-mpi/ompi/issues/13493#issuecomment-3518789742) , I am not even sure this is supposed to work.
Once you update the openmpi source tree, make sure you always run
`git submodule update --init --recursive` and run `autogen.pl` if there were some changes.

**Comment by rhc54** [comment]
Yeah, OMPI main is in some weird state. Best if you just use the internal embedded copies, or use external versions for both PMIx and PRRTE (which is what I recommend as it is unclear if/when this state will get resolved). Mixing external and internal at this time is a formula for trouble (both in compile and execution).

**Comment by ashterenli** [comment]
understood, thank you
